1) Install libraries

In [1]:
!pip install -q -U pypdf pandas google-genai cohere groq huggingface_hub openai

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.3/52.3 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 333.4/333.4 kB 13.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 42.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 733.5/733.5 kB 34.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 323.4/323.4 kB 19.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.7/139.7 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 616.3/616.3 kB 15.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 49.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 56.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.1 which is incompatible.
db-dtypes 1.5.0 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.1 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.1 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.1 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.1 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.1 which is incompatible.

2) Import Libraries

In [2]:
import os
import re
import json
import zipfile
from pathlib import Path
from getpass import getpass

import pandas as pd
from pypdf import PdfReader

from google.colab import files

from google import genai
import cohere
from groq import Groq
from huggingface_hub import InferenceClient
from openai import OpenAI

3) upload zip file

In [3]:
uploaded = files.upload()

Saving FTSP (Week 1)  .zip to FTSP (Week 1)  .zip

4) extract zip file

In [4]:
extract_folder = Path("project_files")
extract_folder.mkdir(exist_ok=True)

zip_filename = list(uploaded.keys())[0]

with zipfile.ZipFile(zip_filename, "r") as zip_ref:
    zip_ref.extractall(extract_folder)

print("Files extracted successfully.\n")

for file in sorted(extract_folder.iterdir()):
    print(file.name)

Files extracted successfully.

1 DV.txt
2 DV.txt
3.txt
4.txt
5.txt
Sr. Staff Engineer, Design Verification.pdf

5) Locate resumes and job description

In [5]:
txt_files = sorted(extract_folder.glob("*.txt"))
pdf_files = sorted(extract_folder.glob("*.pdf"))

print("Resume files found:")
for f in txt_files:
    print("-", f.name)

print("\nPDF files found:")
for f in pdf_files:
    print("-", f.name)

if len(pdf_files) == 0:
    raise FileNotFoundError("No PDF job description found in the extracted folder.")

Resume files found:
- 1 DV.txt
- 2 DV.txt
- 3.txt
- 4.txt
- 5.txt

PDF files found:
- Sr. Staff Engineer, Design Verification.pdf

6) Read all text files

In [6]:
def read_text_file(file_path):
    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
        return f.read()

raw_resumes = {}
for file_path in txt_files:
    raw_resumes[file_path.name] = read_text_file(file_path)

print("Loaded resumes:", len(raw_resumes))
print("\nSample preview:\n")

for name, text in raw_resumes.items():
    print("=" * 80)
    print(name)
    print(text[:500])
    print()

Loaded resumes: 5

Sample preview:

================================================================================
1 DV.txt

Top Skills
AXI
APB
CHI
Languages
English  (Native or Bilingual)
Mandarin  (Limited Working)
Malay  (Native or Bilingual)
Design Verification Engineer
Kulim, Kedah, Malaysia
Summary
Currently working as Design Verification Engineer at Skyechip Sdn
Bhd
Graduated from University of Malaysia Perlis (UniMAP), majoring in
Microelectronic Engineering.
Experience
SkyeChip
Design Verification Engineer
August 2022-Present (1 year 4 months)
Penang, Malaysia
Fuji Electric (M) Sdn Bhd
Manufacturing Engin

================================================================================
2 DV.txt

Top Skills
RTL Coding
RTL Verification
RTL Development
Languages
English
Staff Design Verification
Ho Chi Minh City Metropolitan Area
Experience
BOS Semiconductors
Staff Design Verification Engineer
December 2022-Present (1 year)
HCL Technologies
Technical Lead
March 2022-December 2022 (10 months)
RTL design for clock controller, power control, clock and power hardmacro
integration.
Integration system control block in cpu sub-system.
RTL verification system control.
Clock structure, SDC for sy

================================================================================
3.txt

Principales comptences
C++
Verilog
FPGA
Languages
English  (Limited Working)
Design Verification Leader
Vit Nam
Exprience
CoAsia SEMI Vietnam Co., Ltd
RTL Design Verification Leader
octobre 2020-Present (3 ans 2 mois)
Hanoi, Hanoi, Vietnam
#Verification #RTLDesign #UVM #SystemVerilog #ASIC #SOC #LPDDR4/5
#NoC #IWB #VIP
FPT Software
Hardware Engineer - FPT Global Automative - LSI division
aot 2015-septembre 2020 (5 ans 2 mois)
Hoa Lac Hi-Tech Park
.Apr 2019 - Sept 2020: Hardware Verification En

================================================================================
4.txt

Top Skills
C
C++
Java
Languages
Malay  (Professional Working)
English  (Full Professional)
Chinese (Simplified)  (Native or
Bilingual)
Honors-Awards
UNMC High Achievers' Scholarship
Best Society Award 2016/17
Physical Design Engineer at Intel Corporation
Kulim, Kedah, Malaysia
Summary
Currently working on an Intel's product of the latest technology.
Building in-depth fundamental technical understandings with hands-
on experiences
Experience
Intel Corporation
Physical Design Engineer
August 20

================================================================================
5.txt

Top Skills
Very-Large-Scale Integration (VLSI)
System on a Chip (SoC)
Innovus
Physical design engineer with various experiences in VLSI
Singapore
Summary
Experienced Semiconductor Engineer specializing in Backend digital
design who spent his early career of 4 years in Intel and learned
most of the clock architecture and planning for CPU design. I have
experience in designing clock mesh with spice simulation and top
clock distribution with specially designed strong buffers. On top of
that, I wa

7) Read the job description PDF

In [7]:
def read_pdf_text(pdf_path):
    reader = PdfReader(str(pdf_path))
    text = []
    for page in reader.pages:
        page_text = page.extract_text()
        if page_text:
            text.append(page_text)
    return "\n".join(text)

job_pdf_path = pdf_files[0]
raw_job_description = read_pdf_text(job_pdf_path)

print("Job description file:", job_pdf_path.name)
print("\nPreview:\n")
print(raw_job_description[:1500])

Job description file: Sr. Staff Engineer, Design Verification.pdf

Preview:

Sr. Staff Engineer, Design Verification

Staff Engineer – Design Verification

Client is looking for an experienced Staff Design Verification Engineer to join our dynamic team in
Austin, TX. The ideal candidate will have 8-12 years of experience in the field of semiconductor
design verification, and a proven track record of success in developing and executing verification
plans for complex SoC designs.

Responsibilities:

The Design Verification Engineer will be responsible for verification of digital and mixed-signal
designs, including systems-on-chip with multiple CPUs, and digital signal processors, security
hardware, and other logic for IoT applications.

Specific Responsibilities:
• Ideal candidate should have demonstrated successful design verification tasks at block, sub-
system, and full-chip level.
• Must have participated in all phases of chip development, from creating test plans, creating
testbench environment (SV/UVM), integrate VIP’s, automate test env for randomized testing
and score boarding.
• Utilize UVM to create drivers, monitors, predictors, and scoreboards.
• In-Depth knowledge of SoC architecture with AMBA AXI/AHB/APB, DMA’s, Security, clock,
and power-gating techniques is required.
• Responsible for verification of block(s) that includes writing tests, assertion and coverage for
a block.
• Create tests to achieve coverage goals while verifying functionality.
• Develop support utilities for verification automation, test bench a

8) Text preprocessing

In [8]:
def preprocess_text(text):
    if not isinstance(text, str):
        text = str(text)

    # normalize line breaks / spaces
    text = text.replace("\xa0", " ")
    text = text.replace("\n", " ")
    text = text.replace("\t", " ")

    # lowercase
    text = text.lower()

    # remove phone numbers
    text = re.sub(r'(\+?\d[\d\-\(\) ]{7,}\d)', ' ', text)

    # remove repeated punctuation-like noise but keep useful technical symbols
    # keep letters, digits, spaces, slash, plus, hash, hyphen, dot
    text = re.sub(r'[^a-z0-9/\+\#\-\.\s]', ' ', text)

    # remove multiple dots or dashes if noisy
    text = re.sub(r'[\.]{2,}', ' ', text)
    text = re.sub(r'[-]{2,}', ' ', text)

    # collapse spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

9) Apply preprocessing to resumes and job description

In [9]:
cleaned_resumes = {}
for name, text in raw_resumes.items():
    cleaned_resumes[name] = preprocess_text(text)

cleaned_job_description = preprocess_text(raw_job_description)

print("Cleaned job description preview:\n")
print(cleaned_job_description[:1200])

print("\n\nCleaned resume preview:\n")
for name, text in cleaned_resumes.items():
    print("=" * 80)
    print(name)
    print(text[:400])
    print()

Cleaned job description preview:

sr. staff engineer design verification staff engineer design verification client is looking for an experienced staff design verification engineer to join our dynamic team in austin tx. the ideal candidate will have 8-12 years of experience in the field of semiconductor design verification and a proven track record of success in developing and executing verification plans for complex soc designs. responsibilities the design verification engineer will be responsible for verification of digital and mixed-signal designs including systems-on-chip with multiple cpus and digital signal processors security hardware and other logic for iot applications. specific responsibilities ideal candidate should have demonstrated successful design verification tasks at block sub- system and full-chip level. must have participated in all phases of chip development from creating test plans creating testbench environment sv/uvm integrate vip s automate test env for randomized testing and score boarding. utilize uvm to create drivers monitors predictors and scoreboards. in-depth knowledge of soc architecture with amba axi/ahb/apb dma s security clock and power-gating techniques is required. responsible fo


Cleaned resume preview:

================================================================================
1 DV.txt
top skills axi apb chi languages english native or bilingual mandarin limited working malay native or bilingual design verification engineer kulim kedah malaysia summary currently working as design verification engineer at skyechip sdn bhd graduated from university of malaysia perlis unimap majoring in microelectronic engineering. experience skyechip design verification engineer august 2022-presen

================================================================================
2 DV.txt
top skills rtl coding rtl verification rtl development languages english staff design verification ho chi minh city metropolitan area experience bos semiconductors staff design verification engineer december 2022-present 1 year hcl technologies technical lead march 2022-december 2022 10 months rtl design for clock controller power control clock and power hardmacro integration. integration system c

================================================================================
3.txt
principales comptences c++ verilog fpga languages english limited working design verification leader vit nam exprience coasia semi vietnam co. ltd rtl design verification leader octobre 2020-present 3 ans 2 mois hanoi hanoi vietnam #verification #rtldesign #uvm #systemverilog #asic #soc #lpddr4/5 #noc #iwb #vip fpt software hardware engineer - fpt global automative - lsi division aot 2015-septembr

================================================================================
4.txt
top skills c c++ java languages malay professional working english full professional chinese simplified native or bilingual honors-awards unmc high achievers scholarship best society award 2016/17 physical design engineer at intel corporation kulim kedah malaysia summary currently working on an intel s product of the latest technology. building in-depth fundamental technical understandings with ha

================================================================================
5.txt
top skills very-large-scale integration vlsi system on a chip soc innovus physical design engineer with various experiences in vlsi singapore summary experienced semiconductor engineer specializing in backend digital design who spent his early career of 4 years in intel and learned most of the clock architecture and planning for cpu design. i have experience in designing clock mesh with spice simu

10) Save cleaned text files

In [10]:
cleaned_folder = Path("cleaned_texts")
cleaned_folder.mkdir(exist_ok=True)

for name, text in cleaned_resumes.items():
    out_path = cleaned_folder / f"cleaned_{name}"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)

with open(cleaned_folder / "cleaned_job_description.txt", "w", encoding="utf-8") as f:
    f.write(cleaned_job_description)

print("Cleaned files saved in:", cleaned_folder)
print("\nSaved files:")
for f in sorted(cleaned_folder.iterdir()):
    print("-", f.name)

Cleaned files saved in: cleaned_texts

Saved files:
- cleaned_1 DV.txt
- cleaned_2 DV.txt
- cleaned_3.txt
- cleaned_4.txt
- cleaned_5.txt
- cleaned_job_description.txt

11) preprocessing summary table

In [11]:
summary_rows = []

for name in raw_resumes:
    raw_text = raw_resumes[name]
    cleaned_text = cleaned_resumes[name]

    summary_rows.append({
        "file_name": name,
        "raw_char_count": len(raw_text),
        "cleaned_char_count": len(cleaned_text),
        "removed_chars": len(raw_text) - len(cleaned_text)
    })

summary_rows.append({
    "file_name": "job_description_pdf",
    "raw_char_count": len(raw_job_description),
    "cleaned_char_count": len(cleaned_job_description),
    "removed_chars": len(raw_job_description) - len(cleaned_job_description)
})

summary_df = pd.DataFrame(summary_rows)
summary_df

             file_name  raw_char_count  cleaned_char_count  removed_chars
0             1 DV.txt            2974                2883             91
1             2 DV.txt            1403                1362             41
2                3.txt            1699                1646             53
3                4.txt            4800                4692            108
4                5.txt            4376                4215            161
5  job_description_pdf            2562                2422            140

12) Create prompts

In [12]:
SYSTEM_PROMPT = """
You are an HR screening assistant.
Your task is to compare a candidate's resume with a job description.

Focus on:
1. Relevant technical skills
2. Relevant work experience
3. Overall suitability for the role

Return the answer in a clear and concise format with:
- Candidate Summary
- Matching Skills
- Missing / Weak Areas
- Suitability Score out of 10
"""

In [13]:
def build_user_prompt(job_description, candidate_name, resume_text):
    return f"""
Job Description:
{job_description}

Candidate Resume File Name:
{candidate_name}

Candidate Resume Text:
{resume_text}

Please evaluate this candidate against the job description.

Format your answer as:
Candidate Summary:
Matching Skills:
Missing / Weak Areas:
Suitability Score:
"""

13) Enter API keys

In [14]:
COHERE_API_KEY = getpass("Enter your Cohere API key: ")
GEMINI_API_KEY = getpass("Enter your Gemini API key: ")
GROQ_API_KEY = getpass("Enter your Groq API key: ")
HF_API_KEY = getpass("Enter your Hugging Face API key: ")
OPENROUTER_API_KEY = getpass("Enter your OpenRouter API key: ")

Enter your Cohere API key: ··········
Enter your Gemini API key: ··········
Enter your Groq API key: ··········
Enter your Hugging Face API key: ··········

14) Set up API clients

In [15]:
# Gemini client
gemini_client = genai.Client(api_key=GEMINI_API_KEY)

# Cohere client
co = cohere.ClientV2(api_key=COHERE_API_KEY)

# Groq client
groq_client = Groq(api_key=GROQ_API_KEY)

# HuggingFace client (Qwen2.5-72B by Alibaba)
hf_client = InferenceClient(api_key=HF_API_KEY)

# OpenRouter client (DeepSeek R1 - free, no credit card)
openrouter_client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key="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"
)

15) Gemini response function

In [16]:
def get_gemini_response(system_prompt, user_prompt, model_name="gemini-2.5-flash"):
    full_prompt = f"System Prompt:\n{system_prompt}\n\nUser Prompt:\n{user_prompt}"

    response = gemini_client.models.generate_content(
        model=model_name,
        contents=full_prompt
    )

    return response.text

16) Cohere response function

In [17]:
def get_cohere_response(system_prompt, user_prompt, model_name="command-r-08-2024"):
    response = co.chat(
        model=model_name,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]
    )

    # Cohere V2 responses may return content blocks
    if hasattr(response, "message") and hasattr(response.message, "content"):
        parts = []
        for item in response.message.content:
            if hasattr(item, "text"):
                parts.append(item.text)
            elif isinstance(item, dict) and "text" in item:
                parts.append(item["text"])
        return "\n".join(parts).strip()

    return str(response)

17. Grok Function

In [18]:
def get_groq_response(system_prompt, user_prompt, model_name="llama-3.3-70b-versatile"):
    response = groq_client.chat.completions.create(
        model=model_name,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]
    )
    return response.choices[0].message.content

18. HuggingFace Function

In [19]:
def get_huggingface_response(
    system_prompt,
    user_prompt,
    model_name="Qwen/Qwen2.5-72B-Instruct"
):
    response = hf_client.chat.completions.create(
        model=model_name,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        max_tokens=800
    )
    return response.choices[0].message.content

### OpenRouter Response Function (DeepSeek R1)

DeepSeek R1 is a strong reasoning model from DeepSeek (China). Accessed via OpenRouter — completely free with no credit card required. Adding this 5th API ensures majority vote always produces a clear winner since 5 votes cannot result in a tie.

In [ ]:
def get_openrouter_response(
    system_prompt,
    user_prompt,
    model_name="deepseek/deepseek-r1:free"
):
    response = openrouter_client.chat.completions.create(
        model=model_name,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]
    )
    return response.choices[0].message.content

19) Test one resume first

In [20]:
test_candidate = list(cleaned_resumes.keys())[0]
test_resume = cleaned_resumes[test_candidate]

test_prompt = build_user_prompt(
    job_description=cleaned_job_description,
    candidate_name=test_candidate,
    resume_text=test_resume
)

print("Testing candidate:", test_candidate)

print("\n--- GEMINI OUTPUT ---\n")
try:
    print(get_gemini_response(SYSTEM_PROMPT, test_prompt))
except Exception as e:
    print("Gemini Error:", e)

print("\n--- COHERE OUTPUT ---\n")
try:
    print(get_cohere_response(SYSTEM_PROMPT, test_prompt))
except Exception as e:
    print("Cohere Error:", e)

print("\n--- GROQ OUTPUT ---\n")
try:
    print(get_groq_response(SYSTEM_PROMPT, test_prompt))
except Exception as e:
    print("Groq Error:", e)

print("\n--- HUGGINGFACE (Qwen2.5-72B) OUTPUT ---\n")
try:
    print(get_huggingface_response(SYSTEM_PROMPT, test_prompt))
except Exception as e:
    print("HuggingFace Error:", e)

print("\n--- OPENROUTER (DeepSeek R1) OUTPUT ---\n")
try:
    print(get_openrouter_response(SYSTEM_PROMPT, test_prompt))
except Exception as e:
    print("OpenRouter Error:", e)

Testing candidate: 1 DV.txt

--- GEMINI OUTPUT ---

**Candidate Summary:**
The candidate is currently a Design Verification Engineer with 1 year and 4 months of relevant experience. They hold a Bachelor's degree in Microelectronic Engineering. While they have some foundational knowledge in bus protocols (AXI, APB), their overall experience level and detailed technical skill demonstration fall significantly short of the requirements for a Sr. Staff Design Verification Engineer role.

**Matching Skills:**
*   **Education:** Bachelor of Engineering in Microelectronic Engineering matches the degree type (BSEE/MSEE).
*   **Technical Knowledge:** Explicitly mentions "axi apb chi" as top skills, indicating familiarity with AMBA AXI/AHB/APB and potentially SoC bus architectures.
*   **Role Title:** Currently employed as a Design Verification Engineer.

**Missing / Weak Areas:**
*   **Experience Level:** The most significant mismatch. The job requires 8-12 years of experience in semiconductor design verification, whereas the candidate has only 1 year and 4 months of direct DV experience. Their other work history is in manufacturing, equipment, sales, and delivery, which is not relevant to this role.
*   **Seniority:** The job is for a "Sr. Staff Engineer" which demands a proven track record and leadership skills, neither of which can be demonstrated with the candidate's current experience level.
*   **Specific DV Methodologies/Tools:** The resume lacks specific mention of proficiency in SystemVerilog, UVM (drivers, monitors, predictors, scoreboards), Verilog, C/C++, Python, and Makefile, which are all explicitly required. There is no detail on experience with test plan creation, testbench environment setup, VIP integration, randomized testing, scoreboarding, or automation.
*   **Advanced Concepts:** No mention of experience with mixed-signal designs, low-power design verification challenges, gate-level simulations, FPGA/post-silicon bring-up, ARM processor-based designs, or specific technologies like MIPI, Crypto, OTP, DSP.
*   **SoC Architecture Depth:** While AXI/APB are mentioned, in-depth knowledge of SoC architecture including DMA's, security, clock, and power-gating techniques is not elaborated upon.

**Suitability Score:** 1/10

--- COHERE OUTPUT ---

Candidate Summary:
This candidate is a Design Verification Engineer with a background in microelectronic engineering. They have experience in various industries, including semiconductor manufacturing, equipment engineering, and sales. The candidate has a strong understanding of design verification processes and has worked on projects involving back-end processes, equipment maintenance, and quality control.

Matching Skills:
- Experience in design verification at the block, sub-system, and full-chip levels.
- Knowledge of AMBA AXI/AHB/APB protocols and DMA flow control.
- Proficiency in languages such as SystemVerilog, Verilog, C/C++, and Python.
- Familiarity with low-power design and verification challenges.
- Understanding of mixed-signal designs and their verification.

Missing / Weak Areas:
- The candidate's resume does not explicitly mention 8-12 years of experience in semiconductor design verification, which is a key requirement for the role.
- There is no evidence of working with complex SOC designs or having a proven track record of developing and executing verification plans for such designs.
- The resume lacks specific details about the candidate's involvement in chip development phases, particularly in creating test plans, testbench environments, and integrating VIPs.
- While the candidate has experience with SystemVerilog, there is no mention of experience with UVM, which is a crucial skill for this role.
- The resume does not highlight the candidate's knowledge of SOC architecture and security hardware, which are essential for this position.

Suitability Score: 5/10

The candidate shows potential in design verification and has a strong educational background. However, the lack of specific experience and skills outlined in the job description suggests that further assessment and additional training may be required to meet the role's expectations.

--- GROQ OUTPUT ---

Candidate Summary:
The candidate has a background in microelectronic engineering and has worked as a Design Verification Engineer at Skyechip Sdn Bhd. They have experience in manufacturing, equipment engineering, and sales, but their relevant work experience in design verification is limited to 1 year and 4 months. They have a strong educational foundation in microelectronic engineering, but their skills and experience may not fully align with the requirements of the job description.

Matching Skills:
- The candidate has experience with AXI and APB, which are relevant to the job description.
- They have a background in microelectronic engineering, which is relevant to the field of semiconductor design verification.
- They have experience working with equipment and troubleshooting, which may be transferable to a design verification role.

Missing / Weak Areas:
- The candidate lacks extensive experience in design verification, with only 1 year and 4 months of experience in this field.
- They do not have a strong background in SystemVerilog, UVM, or other relevant programming languages.
- They lack experience with SOC architecture, including AMBA, AXI/AHB/APB, DMA, and security, which is a critical requirement for the job.
- They do not have experience with low-power design and verification challenges, which is a highly desired skill for the job.

Suitability Score: 4/10
The candidate has some relevant skills and experience, but they lack the extensive experience and technical expertise required for the job. They may require significant training and development to meet the requirements of the role.

--- HUGGING FACE OUTPUT ---

Candidate Summary:
The candidate is a Design Verification Engineer with 1 year 4 months of experience in the field, currently working at Skyechip Sdn Bhd in Malaysia. They have a background in microelectronic engineering and have worked in various roles, including manufacturing engineer, equipment engineer, and sales associate. However, their experience is limited, and most of their work experience is not directly related to semiconductor design verification.

Matching Skills:
- The candidate has mentioned AXI and APB, which are relevant to the job description.
- They have a degree in Microelectronic Engineering, which is relevant to the field.
- They have experience working with design verification, although it is limited to 1 year 4 months.

Missing / Weak Areas:
- The candidate lacks experience in SystemVerilog, UVM, and Verilog, which are essential skills for the job.
- They do not have experience working with SOC designs, mixed-signal designs, or low-power design and verification challenges.
- They have not worked with ARM processor-based designs, AMBA, or other relevant technologies.
- The candidate's experience is limited to 1 year 4 months, which is significantly less than the 8-12 years of experience required by the job description.

Suitability Score: 2/10
The candidate's limited experience and lack of relevant technical skills make them a weak fit for the Senior Staff Engineer - Design Verification role. They would need significant training and experience to meet the requirements of the job.

20) Run all resumes through models

In [21]:
results = []

for candidate_name, resume_text in cleaned_resumes.items():
    user_prompt = build_user_prompt(
        job_description=cleaned_job_description,
        candidate_name=candidate_name,
        resume_text=resume_text
    )

    print(f"Processing {candidate_name}...")

    try:
        gemini_output = get_gemini_response(SYSTEM_PROMPT, user_prompt)
    except Exception as e:
        gemini_output = f"Gemini Error: {e}"

    try:
        cohere_output = get_cohere_response(SYSTEM_PROMPT, user_prompt)
    except Exception as e:
        cohere_output = f"Cohere Error: {e}"

    try:
        groq_output = get_groq_response(SYSTEM_PROMPT, user_prompt)
    except Exception as e:
        groq_output = f"Groq Error: {e}"

    try:
        huggingface_output = get_huggingface_response(SYSTEM_PROMPT, user_prompt)
    except Exception as e:
        huggingface_output = f"HuggingFace Error: {e}"

    try:
        openrouter_output = get_openrouter_response(SYSTEM_PROMPT, user_prompt)
    except Exception as e:
        openrouter_output = f"OpenRouter Error: {e}"

    results.append({
        "candidate_name": candidate_name,
        "gemini_output": gemini_output,
        "cohere_output": cohere_output,
        "groq_output": groq_output,
        "huggingface_output": huggingface_output,
        "openrouter_output": openrouter_output
    })

print("Done.")

Processing 1 DV.txt...
Processing 2 DV.txt...
Processing 3.txt...
Processing 4.txt...
Processing 5.txt...
Done.

21) View all results

In [22]:
for item in results:
    print("=" * 100)
    print("Candidate:", item["candidate_name"])
    print("\nGEMINI RESPONSE:\n")
    print(item["gemini_output"])
    print("\nCOHERE RESPONSE:\n")
    print(item["cohere_output"])
    print("\nGROQ RESPONSE:\n")
    print(item["groq_output"])
    print("\nHUGGINGFACE (Qwen2.5-72B) RESPONSE:\n")
    print(item["huggingface_output"])
    print("\nOPENROUTER (DeepSeek R1) RESPONSE:\n")
    print(item["openrouter_output"])
    print()

====================================================================================================
Candidate: 1 DV.txt

GEMINI RESPONSE:

Gemini Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 51.981325139s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '51s'}]}}

COHERE RESPONSE:

Candidate Summary:
This candidate is a Design Verification Engineer with a background in microelectronic engineering. They have experience in the semiconductor industry and have worked with various companies, including Intel Corporation and Silterra Malaysia. The candidate's resume highlights their skills in design verification, manufacturing, and equipment engineering.

Matching Skills:
- Experience in design verification at the block, sub-system, and full-chip levels.
- Knowledge of AXI, APB, and other semiconductor architectures.
- Proficiency in languages such as SystemVerilog, Verilog, C/C++, and Python, which are relevant to the role.
- Understanding of low-power design and verification, a key aspect of the job description.
- Familiarity with ARM-based designs and processor technologies.

Missing / Weak Areas:
- The candidate's resume lacks specific details about their involvement in creating test plans, testbench environments, and verification plans, which are crucial aspects of the role.
- There is no mention of experience with UVM (Universal Verification Methodology) or its utilization for creating drivers, monitors, predictors, and scoreboards.
- While the candidate has worked with mixed-signal designs, their experience with low-power design and verification challenges is not explicitly highlighted.
- The resume does not provide information on their participation in all phases of chip development, including integration of 3rd party IP/VIPs.
- Preferred technologies such as MIPI, Crypto, and DSP are not mentioned in the candidate's skill set.

Suitability Score: 6/10

GROQ RESPONSE:

Candidate Summary:
The candidate is a Design Verification Engineer with 1 year 4 months of experience in design verification at Skyechip Sdn Bhd. The candidate has a Bachelor's degree in Microelectronic Engineering from Universiti Malaysia Perlis and a Diploma in Electronic Engineering. The candidate has worked in various roles, including manufacturing engineer, equipment engineer, and sales associate, but their experience in design verification is limited to their current role.

Matching Skills:
- The candidate has experience with AXI and APB, which are relevant protocols mentioned in the job description.
- The candidate is familiar with design verification, which is the primary responsibility of the job.
- The candidate has a strong educational background in Microelectronic Engineering.

Missing / Weak Areas:
- The candidate lacks experience in SystemVerilog, UVM, and Verilog, which are essential skills required for the job.
- The candidate does not have experience with SOC architecture, including AMBA, AHB, and security hardware.
- The candidate's experience in design verification is limited to 1 year 4 months, which is less than the 8-12 years of experience required for the job.
- The candidate does not have experience with low-power design and verification challenges, which is a highly desired skill for the job.
- The candidate's experience with C-based verification in an SOC environment is not mentioned.

Suitability Score: 4/10
The candidate has some relevant skills and experience, but they lack the essential technical skills and experience required for the job. The candidate's limited experience in design verification and lack of experience with SystemVerilog, UVM, and Verilog are significant weaknesses. However, the candidate's strong educational background and familiarity with AXI and APB protocols make them a potential candidate for further training and development.

HUGGING FACE RESPONSE:

Candidate Summary:
The candidate is a Design Verification Engineer with 1 year 4 months of experience in the field, currently working at Skyechip Sdn Bhd in Malaysia. They have a Bachelor's degree in Microelectronic Engineering and a Diploma in Electronic Engineering. Their experience is primarily in manufacturing and equipment engineering, with some background in design verification.

Matching Skills:
- The candidate has mentioned AXI and APB as part of their top skills, which matches the job description's requirement for in-depth knowledge of SOC architecture with AMBA AXI/AHB/APB.
- They have experience working with design verification, although the extent of this experience is not clearly detailed.
- The candidate has a strong educational background in Microelectronic Engineering, which is relevant to the field of semiconductor design verification.

Missing / Weak Areas:
- The candidate lacks significant experience in the field of semiconductor design verification, with only 1 year 4 months of experience, whereas the job description requires 8-12 years of experience.
- There is no mention of experience with SystemVerilog, UVM, or other required technologies such as ARM, SOC, or low-power design techniques.
- The candidate's experience is mostly in manufacturing and equipment engineering, which may not be directly applicable to the role of a Design Verification Engineer.
- There is no evidence of the candidate's ability to develop and execute verification plans for complex SOC designs, or their experience with gate-level simulations, FPGA, and post-silicon bring-up.

Suitability Score: 2/10
The candidate's lack of significant experience in design verification, limited skills in required technologies, and mostly non-relevant work experience make them a less suitable candidate for the Senior Staff Engineer - Design Verification position. However, their educational background and some matching skills may make them a potential candidate for a junior or entry-level position in the field.

====================================================================================================
Candidate: 2 DV.txt

GEMINI RESPONSE:

Gemini Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 39.814392868s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '39s'}]}}

COHERE RESPONSE:

Candidate Summary:
This candidate has a strong background in RTL design, verification, and development, with a focus on semiconductor and SoC (System-on-Chip) projects. They have experience in various aspects of the design process, including RTL coding, verification, and integration.

Matching Skills:
- RTL Coding and Verification: The candidate has extensive experience in RTL design and verification, which is a key requirement for the role.
- SystemVerilog and UVM: Proficiency in SystemVerilog and UVM is evident from their resume, aligning with the job's needs.
- Mixed-Signal Design: With a background in mixed-signal designs, the candidate meets the job's requirement for experience in this area.
- Low-Power Design: The candidate's experience with low-power design techniques and battery-operated designs is a strong match for the job description.
- ARM Processor-Based Designs: Their work with ARM processor-based designs is an advantage, as the job prefers experience in this domain.

Missing / Weak Areas:
- Verification at Different Levels: While the candidate has experience in RTL verification, the job description emphasizes verification at the block, sub-system, and full-chip levels. More specific details on their experience in these areas would be beneficial.
- Automation and Testbench Development: The job requires developing testbench environments and automating tests, which is not explicitly mentioned in the candidate's resume.
- Python and Makefile Skills: Proficiency in Python and Makefile technologies, as mentioned in the job description, is not highlighted in the candidate's skills.

Suitability Score: 7/10

GROQ RESPONSE:

Candidate Summary:
The candidate has over 8 years of experience in the field of semiconductor design verification, with a strong background in RTL coding, verification, and development. They have worked with various companies, including Bos Semiconductors, HCL Technologies, and Renesas Design Vietnam Co. Ltd., and have experience with multiple architectures, including AXI/AHB/APB and low-power design techniques.

Matching Skills:
- 8+ years of experience in design verification
- Strong understanding of RTL coding, verification, and development
- Experience with AXI/AHB/APB and low-power design techniques
- Familiarity with SystemVerilog, Verilog, and C/C++ programming languages
- Knowledge of design verification methodologies, including VMM and formal verification
- Experience with FPGA and STA (Static Timing Analysis)

Missing / Weak Areas:
- Limited experience with UVM (Universal Verification Methodology) and scored boarding
- No explicit mention of experience with ARM processor-based designs, although they have worked with CPU sub-systems
- No direct experience with System-on-Chip (SoC) verification, although they have worked with complex digital and mixed-signal designs
- No explicit mention of experience with design verification for low-power battery-operated designs, although they have worked with low-power design techniques

Suitability Score: 7.5/10
The candidate has a strong background in design verification and RTL development, with relevant experience in AXI/AHB/APB and low-power design techniques. However, they may require additional training or experience in UVM, scored boarding, and SoC verification to fully meet the job requirements. Overall, they are a strong candidate, but may need to develop some additional skills to be fully suitable for the role.

HUGGING FACE RESPONSE:

Candidate Summary:
The candidate has around 12 years of experience in the field of semiconductor design verification, with a strong background in RTL coding, verification, and development. They have worked with various companies, including Bos Semiconductors, HCL Technologies, and Renesas Design Vietnam Co. Ltd., and have experience with system control blocks, clock and power management, and verification methodologies like VMM.

Matching Skills:
- Experience in design verification for digital and mixed-signal designs
- Knowledge of SOC architecture, including AMBA AXI/AHB/APB and DMA
- Strong understanding of RTL coding and verification
- Experience with system verification methodologies (VMM)
- Familiarity with languages like SystemVerilog, Verilog, and C/C++
- Experience with formal verification, STA, and AC-timing

Missing / Weak Areas:
- Limited experience with UVM (only VMM methodology mentioned)
- No explicit mention of experience with low-power design and verification challenges, although they have worked with power control and clock management
- No direct experience with ARM processor-based designs mentioned
- Limited experience with Python, Makefile, and other technologies mentioned in the job description
- No explicit mention of experience with gate-level simulations, FPGA, and post-silicon bring-up

Suitability Score: 7.5/10
The candidate has a strong background in design verification and relevant technical skills, but lacks experience in some specific areas mentioned in the job description, such as UVM, low-power design, and ARM processor-based designs. However, their overall experience and skills make them a suitable candidate for the role, with some potential for growth and training in the missing areas.

====================================================================================================
Candidate: 3.txt

GEMINI RESPONSE:

Gemini Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 28.205261516s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '28s'}]}}

COHERE RESPONSE:

Candidate Summary:
The candidate has a strong background in hardware and software engineering, with a focus on design verification and RTL design. They have experience in leading verification teams and managing projects.

Matching Skills:
- Proficiency in SystemVerilog, UVM, and C/C++ for verification tasks.
- Knowledge of RTL design and FPGA development.
- Experience with SystemC and high-level synthesis for hardware modeling.
- Understanding of computer architecture and project management.
- Familiarity with low-power design and verification challenges.

Missing / Weak Areas:
- The candidate's resume does not explicitly mention experience with mixed-signal designs, which is a key requirement in the job description.
- There is no indication of working with ARM-based designs or low-power design techniques, which are preferred skills for the role.
- While the candidate has experience in verification at the block and subsystem levels, there is no mention of full-chip verification, which is a specific qualification mentioned in the job description.

Suitability Score: 7/10

GROQ RESPONSE:

Candidate Summary:
The candidate has a strong background in design verification, with experience in RTL design verification, hardware verification, and software development. They have worked with various technologies, including SystemVerilog, UVM, Verilog, C++, and Python. The candidate also has experience in project management and has managed a team of 8 members.

Matching Skills:
- Experience in design verification, including RTL design verification and hardware verification
- Strong understanding of SystemVerilog, UVM, and Verilog
- Familiarity with C++ and Python programming languages
- Experience with FPGA and ASIC design
- Knowledge of AXI, AHB, and APB bus systems
- Background in computer architecture and hardware development
- Experience with low-power design and verification challenges

Missing / Weak Areas:
- The candidate's experience in SOC architecture, specifically with AMBA, DMA, and security hardware, is not explicitly mentioned
- No direct experience with ARM processor-based designs is mentioned
- Although the candidate has experience with low-power design and verification, there is no specific mention of experience with battery-operated designs
- Limited experience with MIPS, CSI/DSI, Crypto, and OTP technologies

Suitability Score: 7.5/10
The candidate has a strong foundation in design verification and relevant technical skills, but may require additional training or experience in specific areas, such as SOC architecture, ARM processor-based designs, and low-power design techniques. Overall, the candidate is a good fit for the role, but may need to develop some additional skills to meet the full requirements of the position.

HUGGING FACE RESPONSE:

Candidate Summary:
The candidate has around 8 years of experience in the field of semiconductor design verification, with a strong background in RTL design verification, UVM, SystemVerilog, and Verilog. They have worked on various projects, including hardware verification, modeling, and design, and have experience with languages such as C++, SystemC, and Python. They also have a degree in Electrical, Electronic, and Communications Engineering Technology.

Matching Skills:
- Experience in design verification, including RTL design verification and UVM
- Strong understanding of SystemVerilog, Verilog, and C++
- Familiarity with SOC architecture, including AXI, AHB, and APB
- Experience with hardware modeling and virtual platform development
- Knowledge of languages such as Python and C
- Experience with FPGA and ASIC design

Missing / Weak Areas:
- Lack of direct experience with low-power design and verification challenges, although they have worked on projects related to LPDD4/5
- Limited experience with ARM processor-based designs and low-power design techniques
- No direct mention of experience with gate-level simulations, post-silicon bring-up, or MIPS, CSI/DSI, Crypto, OTP, or DSP
- Limited experience with 3rd party IP/VIP integration and SystemVerilog simulation in an SOC environment

Suitability Score: 7.5/10
The candidate has a strong background in design verification and relevant technical skills, but lacks some specific experience and expertise required for the job, such as low-power design and verification challenges, ARM processor-based designs, and gate-level simulations. However, their overall experience and skills make them a suitable candidate for the role, and they may be able to learn and adapt to the specific requirements of the job.

====================================================================================================
Candidate: 4.txt

GEMINI RESPONSE:


### **Recomendation Section**

22. Score Extraction

In [23]:
def extract_score(text):
    """
    Extracts a score out of 10 from model output.
    Handles formats like:
      7/10, 7.5/10, **Score:** 7/10, 7 out of 10
    """
    if not isinstance(text, str):
        return None

    # Handle X/10 format (works even with bold markdown around it)
    match = re.search(r"(\d+(?:\.\d+)?)\s*/\s*10", text)
    if match:
        return float(match.group(1))

    # Handle "X out of 10" format
    match = re.search(r"(\d+(?:\.\d+)?)\s*out\s*of\s*10", text, re.IGNORECASE)
    if match:
        return float(match.group(1))

    # Handle "Score: X" as fallback
    match = re.search(r"(?:score|rating)[:\s*_]*(\d+(?:\.\d+)?)", text, re.IGNORECASE)
    if match:
        val = float(match.group(1))
        if 0 <= val <= 10:
            return val

    return None

23. Score Table

In [24]:
score_rows = []

for item in results:
    score_rows.append({
        "candidate_name": item["candidate_name"],
        "gemini_score": extract_score(item["gemini_output"]),
        "cohere_score": extract_score(item["cohere_output"]),
        "groq_score": extract_score(item["groq_output"]),
        "huggingface_score": extract_score(item["huggingface_output"]),
        "openrouter_score": extract_score(item["openrouter_output"]),
    })

scores_df = pd.DataFrame(score_rows)
scores_df

  candidate_name gemini_score  cohere_score  groq_score  huggingface_score
0       1 DV.txt         None           6.0         4.0                2.0
1       2 DV.txt         None           7.0         7.5                7.5
2          3.txt         None           7.0         7.5                7.5
3          4.txt         None           5.0         4.0                4.0
4          5.txt         None           6.0         4.0                4.0

24. Average Score

In [25]:
score_columns = ["gemini_score", "cohere_score", "groq_score", "huggingface_score"]

scores_df["average_score"] = scores_df[score_columns].mean(axis=1, skipna=True)
scores_df = scores_df.sort_values(by="average_score", ascending=False)

scores_df

,candidate_name,gemini_score,cohere_score,groq_score,huggingface_score,average_score
1,2 DV.txt,None,7.0,7.5,7.5,7.333333
2,3.txt,None,7.0,7.5,7.5,7.333333
4,5.txt,None,6.0,4.0,4.0,4.666667
3,4.txt,None,5.0,4.0,4.0,4.333333
0,1 DV.txt,None,6.0,4.0,2.0,4.0

ALL COMBINED RESULTS

In [26]:
from collections import Counter

score_columns = ["gemini_score", "cohere_score", "groq_score", "huggingface_score"]

# Find top candidate for each model
model_recommendations = {}

for col in score_columns:
    valid_df = scores_df.dropna(subset=[col])
    if not valid_df.empty:
        top_candidate = valid_df.sort_values(by=col, ascending=False).iloc[0]["candidate_name"]
        model_recommendations[col] = top_candidate

print("Top recommendation by each LLM:\n")
for model_name, candidate in model_recommendations.items():
    print(f"{model_name}: {candidate}")

# Majority vote
votes = list(model_recommendations.values())
vote_counter = Counter(votes)

print("\nMajority vote result:\n")
for candidate, count in vote_counter.items():
    print(f"{candidate}: {count} vote(s)")

majority_best_candidate = vote_counter.most_common(1)[0][0]

# Best candidate by average score
best_average_candidate = scores_df.sort_values(by="average_score", ascending=False).iloc[0]["candidate_name"]

print("\nBest resume based on average score:", best_average_candidate)

# Final decision
if majority_best_candidate == best_average_candidate:
    final_best_candidate = majority_best_candidate
else:
    final_best_candidate = best_average_candidate

print("\nFINAL RECOMMENDED RESUME:", final_best_candidate)

Top recommendation by each LLM:

cohere_score: 2 DV.txt
groq_score: 2 DV.txt
huggingface_score: 2 DV.txt

Majority vote result:

2 DV.txt: 3 vote(s)

Best resume based on average score: 2 DV.txt

FINAL RECOMMENDED RESUME: 2 DV.txt

preprcessing testing

In [27]:
candidate = list(raw_resumes.keys())[0]

print("RAW TEXT:\n")
print(raw_resumes[candidate][:500])

print("\n" + "="*60 + "\n")

print("CLEANED TEXT:\n")
print(cleaned_resumes[candidate][:500])

RAW TEXT:


Top Skills
AXI
APB
CHI
Languages
English  (Native or Bilingual)
Mandarin  (Limited Working)
Malay  (Native or Bilingual)
Design Verification Engineer
Kulim, Kedah, Malaysia
Summary
Currently working as Design Verification Engineer at Skyechip Sdn
Bhd
Graduated from University of Malaysia Perlis (UniMAP), majoring in
Microelectronic Engineering.
Experience
SkyeChip
Design Verification Engineer
August 2022-Present (1 year 4 months)
Penang, Malaysia
Fuji Electric (M) Sdn Bhd
Manufacturing Engin

============================================================

CLEANED TEXT:

top skills axi apb chi languages english native or bilingual mandarin limited working malay native or bilingual design verification engineer kulim kedah malaysia summary currently working as design verification engineer at skyechip sdn bhd graduated from university of malaysia perlis unimap majoring in microelectronic engineering. experience skyechip design verification engineer august 2022-present 1 year 4 months penang malaysia fuji electric m sdn bhd manufacturing engineer april 2022-august 2

In [28]:
for name in raw_resumes:
    raw_len = len(raw_resumes[name])
    clean_len = len(cleaned_resumes[name])

    print(name)
    print("Raw length:", raw_len)
    print("Cleaned length:", clean_len)
    print("Removed characters:", raw_len - clean_len)
    print()

1 DV.txt
Raw length: 2974
Cleaned length: 2883
Removed characters: 91

2 DV.txt
Raw length: 1403
Cleaned length: 1362
Removed characters: 41

3.txt
Raw length: 1699
Cleaned length: 1646
Removed characters: 53

4.txt
Raw length: 4800
Cleaned length: 4692
Removed characters: 108

5.txt
Raw length: 4376
Cleaned length: 4215
Removed characters: 161

In [29]:
import re

for name, text in cleaned_resumes.items():
    emails = re.findall(r'\S+@\S+', text)

    if emails:
        print(name, "Still has email:", emails)
    else:
        print(name, "No emails found")

1 DV.txt No emails found
2 DV.txt No emails found
3.txt No emails found
4.txt No emails found
5.txt No emails found

---
# WEEK 3 — RAG (Retrieval-Augmented Generation) with LangChain

### 25) Install LangChain and RAG dependencies

In [30]:
!pip install -q langchain langchain-community langchain-core langchain-text-splitters langchain-huggingface faiss-cpu sentence-transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 48.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 81.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 67.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 503.5/503.5 kB 32.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 5.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.1 which is incompatible.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.32.5 which is incompatible.

### 26) Import RAG libraries

In [31]:
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings

### 27) Convert cleaned resumes into LangChain Documents

Each resume becomes a `Document` object with metadata (filename). This is the **data ingestion** step of RAG.

In [32]:
documents = []

for filename, text in cleaned_resumes.items():
    doc = Document(
        page_content=text,
        metadata={"source": filename}
    )
    documents.append(doc)

print(f"Total documents loaded: {len(documents)}")
for doc in documents:
    print(f"  - {doc.metadata['source']} ({len(doc.page_content)} chars)")

Total documents loaded: 5
  - 1 DV.txt (2883 chars)
  - 2 DV.txt (1362 chars)
  - 3.txt (1646 chars)
  - 4.txt (4692 chars)
  - 5.txt (4215 chars)

### 28) Split documents into chunks

Resumes are split into smaller overlapping chunks so the retriever can find the most relevant *sections* rather than searching whole documents at once.

In [33]:
# chunk_size=400 chosen based on resume length (~1500-3000 chars after preprocessing)
# Gives ~4-8 chunks per resume — granular enough without losing context
splitter = RecursiveCharacterTextSplitter(
    chunk_size=400,
    chunk_overlap=80
)

chunks = splitter.split_documents(documents)

print(f"Total chunks created: {len(chunks)}")
print(f"\nSample chunk:")
print(chunks[0].page_content)
print(f"\nFrom file: {chunks[0].metadata['source']}")

Total chunks created: 38

Sample chunk:
top skills axi apb chi languages english native or bilingual mandarin limited working malay native or bilingual design verification engineer kulim kedah malaysia summary currently working as design verification engineer at skyechip sdn bhd graduated from university of malaysia perlis unimap majoring in microelectronic engineering. experience skyechip design verification engineer august 2022-present 1 year 4 months penang malaysia fuji electric m sdn bhd manufacturing engineer april 2022-august

From file: 1 DV.txt

### 29) Load embedding model

We use a free HuggingFace sentence-transformer model to convert text into vector embeddings. These embeddings capture the *semantic meaning* of text, so similar concepts map to nearby vectors.

In [34]:
embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# Quick test
test_embedding = embedding_model.embed_query("software engineer python")
print(f"Embedding model loaded successfully.")
print(f"Embedding dimensions: {len(test_embedding)}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding model loaded successfully.
Embedding dimensions: 384

### 30) Build FAISS Vector Store

FAISS (Facebook AI Similarity Search) stores all the resume chunks as vectors and enables fast similarity search. This is the core of RAG — instead of sending entire resumes to the LLM, we retrieve only the most relevant chunks.

In [35]:
vectorstore = FAISS.from_documents(chunks, embedding_model)

print("FAISS vector store built successfully.")
print(f"Total vectors stored: {vectorstore.index.ntotal}")

FAISS vector store built successfully.
Total vectors stored: 38

### 31) Test RAG Retrieval

Given the job description as a query, retrieve the top-K most semantically similar resume chunks. This simulates what RAG does — finding the most relevant context before passing to the LLM.

In [36]:
retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

# Use first 500 chars of job description as query
query = cleaned_job_description[:500]

retrieved_docs = retriever.invoke(query)

print(f"Query (first 200 chars):\n{query[:200]}\n")
print(f"Retrieved {len(retrieved_docs)} relevant chunks:\n")
for i, doc in enumerate(retrieved_docs):
    print(f"--- Chunk {i+1} (from: {doc.metadata['source']}) ---")
    print(doc.page_content[:300])
    print()

Query (first 200 chars):
sr. staff engineer design verification staff engineer design verification client is looking for an experienced staff design verification engineer to join our dynamic team in austin tx. the ideal candi

Retrieved 3 relevant chunks:

--- Chunk 1 (from: 1 DV.txt) ---
top skills axi apb chi languages english native or bilingual mandarin limited working malay native or bilingual design verification engineer kulim kedah malaysia summary currently working as design verification engineer at skyechip sdn bhd graduated from university of malaysia perlis unimap majoring

--- Chunk 2 (from: 4.txt) ---
hands- on experiences experience intel corporation physical design engineer august 2018-present 5 years 6 months malaysia assigned to work on the next generation of data center product alongside with a strong existing sd team empowering the future experience of computing devices. tasks mainly includ

--- Chunk 3 (from: 2 DV.txt) ---
top skills rtl coding rtl verification rtl development languages english staff design verification ho chi minh city metropolitan area experience bos semiconductors staff design verification engineer december 2022-present 1 year hcl technologies technical lead march 2022-december 2022 10 months rtl d

### 32) RAG-Enhanced screening function

Instead of sending the full resume, RAG retrieves only the most relevant chunks of each resume relative to the job description. This makes the LLM prompt more focused and accurate.

In [37]:
def get_rag_context(candidate_name, job_description_query, k=3):
    """
    Retrieve the most relevant chunks from a specific candidate's resume
    based on the job description query.
    """
    candidate_docs = [c for c in chunks if c.metadata["source"] == candidate_name]

    if not candidate_docs:
        return ""

    candidate_vectorstore = FAISS.from_documents(candidate_docs, embedding_model)
    candidate_retriever = candidate_vectorstore.as_retriever(
        search_kwargs={"k": min(k, len(candidate_docs))}
    )

    retrieved = candidate_retriever.invoke(job_description_query)
    rag_context = "\n\n".join([doc.page_content for doc in retrieved])
    return rag_context

# Test it
test_candidate = list(cleaned_resumes.keys())[0]
rag_ctx = get_rag_context(test_candidate, cleaned_job_description[:500])
print(f"RAG context for {test_candidate}:\n")
print(rag_ctx[:600])

RAG context for 1 DV.txt:

top skills axi apb chi languages english native or bilingual mandarin limited working malay native or bilingual design verification engineer kulim kedah malaysia summary currently working as design verification engineer at skyechip sdn bhd graduated from university of malaysia perlis unimap majoring in microelectronic engineering. experience skyechip design verification engineer august 2022-present 1 year 4 months penang malaysia fuji electric m sdn bhd manufacturing engineer april 2022-august

sdn. bhd. equipment technician december 2016-october 2017 11 months kulim kedah malaysia - repair se

### 33) Build RAG-enhanced prompt

The key difference: instead of the full resume text, we now pass the *retrieved relevant chunks* to the LLM. This is more focused and token-efficient.

In [38]:
def build_rag_user_prompt(job_description, candidate_name, rag_context):
    return f"""
Job Description:
{job_description}

Candidate Resume File Name:
{candidate_name}

Most Relevant Resume Sections (retrieved via RAG):
{rag_context}

Based on the retrieved resume sections above, please evaluate this candidate against the job description.

Format your answer as:
Candidate Summary:
Matching Skills:
Missing / Weak Areas:
Suitability Score:
"""

---
# WEEK 4 — Refine, Compare RAG vs Non-RAG, and Final Recommendation

### 34) Run ALL resumes through RAG-enhanced pipeline

For each candidate, we retrieve their most relevant resume chunks via RAG, then pass those chunks to all 4 LLMs.

In [39]:
for item in rag_results:
    print("=" * 100)
    print("Candidate:", item["candidate_name"])
    print(f"RAG context size: {item['rag_context_length']} chars")
    print("\nGEMINI (RAG) RESPONSE:\n")
    print(item["gemini_output"])
    print("\nCOHERE (RAG) RESPONSE:\n")
    print(item["cohere_output"])
    print("\nGROQ (RAG) RESPONSE:\n")
    print(item["groq_output"])
    print("\nHUGGINGFACE Qwen2.5-72B (RAG) RESPONSE:\n")
    print(item["huggingface_output"])
    print("\nOPENROUTER DeepSeek R1 (RAG) RESPONSE:\n")
    print(item["openrouter_output"])
    print()

Original chunks (size=500): 38
Refined chunks  (size=300): 67
Using refined vectorstore for Week 4 RAG pipeline.

Processing (RAG refined): 1 DV.txt...
Processing (RAG refined): 2 DV.txt...
Processing (RAG refined): 3.txt...
Processing (RAG refined): 4.txt...
Processing (RAG refined): 5.txt...

RAG refined pipeline complete.

### 35) View RAG results

In [40]:
for item in rag_results:
    print("=" * 100)
    print("Candidate:", item["candidate_name"])
    print(f"RAG context size: {item['rag_context_length']} chars")

    print("\nGEMINI (RAG) RESPONSE:\n")
    print(item["gemini_output"])

    print("\nCOHERE (RAG) RESPONSE:\n")
    print(item["cohere_output"])

    print("\nGROQ (RAG) RESPONSE:\n")
    print(item["groq_output"])

    print("\nHUGGING FACE (RAG) RESPONSE:\n")
    print(item["huggingface_output"])
    print()

====================================================================================================
Candidate: 1 DV.txt
RAG context size: 1150 chars

GEMINI (RAG) RESPONSE:

Gemini Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 4.18845423s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '4s'}]}}

COHERE (RAG) RESPONSE:

Candidate Summary:
The candidate is a Design Verification Engineer with a background in microelectronic engineering. They have experience working with semiconductor companies in Malaysia and have a strong understanding of design verification processes.

Matching Skills:
- Proficiency in languages such as SystemVerilog, Verilog, C/C++, and Python, which are essential for design verification tasks.
- Knowledge of AMBA AXI/APB protocols and experience with low-power design and verification challenges.
- Familiarity with mixed-signal designs and the ability to work with 3rd party IPs/VIPs.
- Experience in creating test plans, testbenches, and automating test environments, which aligns with the job's requirements.

Missing / Weak Areas:
- The candidate's resume does not explicitly mention experience with full-chip verification, which is a key requirement for the role.
- There is no mention of working with complex SoCs, multiple CPUs, or digital signal processors, which are critical aspects of the job description.
- The resume lacks details about the candidate's involvement in the entire chip development process, including gate-level simulations and post-silicon bring-up.
- Experience with ARM processor-based designs and low-power design techniques is preferred but not evident from the provided resume sections.

Suitability Score: 6/10

While the candidate demonstrates a solid foundation in design verification and relevant technical skills, there are some key areas where their experience seems to fall short of the job's requirements. More information about their full-chip verification experience and involvement in complex SoC projects would be beneficial for a more accurate assessment.

GROQ (RAG) RESPONSE:

Candidate Summary:
The candidate is a Design Verification Engineer with 1 year and 4 months of experience in the field, currently working at Skyechip Sdn Bhd in Malaysia. They have a background in microelectronic engineering and have worked in various roles, including manufacturing engineer and equipment technician.

Matching Skills:
- The candidate has experience as a Design Verification Engineer, which matches the job description.
- They have knowledge of AXI and APB, which are mentioned in the job description as required skills.
- They have a degree in microelectronic engineering, which is relevant to the field of semiconductor design verification.

Missing / Weak Areas:
- The candidate lacks experience in system-on-chip (SoC) design verification, which is a key requirement of the job description.
- They do not have experience with SystemVerilog, UVM, or other verification languages mentioned in the job description.
- The candidate has limited experience, with only 1 year and 4 months in the field, whereas the job description requires 8-12 years of experience.
- There is no mention of experience with low-power design and verification, arm processor-based designs, or other specific technologies mentioned in the job description.

Suitability Score: 2 out of 10
The candidate's limited experience and lack of specific technical skills required for the job make them a less suitable candidate for the Senior Staff Engineer - Design Verification position.

HUGGING FACE (RAG) RESPONSE:

Candidate Summary:
The candidate is a Design Verification Engineer with 1 year 4 months of experience in the field, currently working at Skyechip Sdn Bhd in Malaysia. They have a background in microelectronic engineering and have worked on design verification, as well as manufacturing and equipment maintenance roles.

Matching Skills:
- The candidate has experience as a Design Verification Engineer, which matches the job description.
- They have knowledge of AXI and APB, which are relevant protocols mentioned in the job description.
- The candidate has a degree in Microelectronic Engineering, which is relevant to the field of semiconductor design verification.

Missing / Weak Areas:
- The candidate lacks the required 8-12 years of experience in the field of semiconductor design verification.
- There is no mention of experience with SystemVerilog, UVM, or other relevant verification tools and methodologies.
- The candidate's experience with SOC architecture, low-power design, and verification challenges is not explicitly mentioned.
- The candidate does not have direct experience with ARM processor-based designs, low-power design techniques, or other preferred technologies.

Suitability Score: 2/10
The candidate's limited experience and lack of direct relevance to the job description's requirements make them a less suitable fit for the Senior Staff Engineer - Design Verification role. However, they may have potential for growth and development in the field with further training and experience.

====================================================================================================
Candidate: 2 DV.txt
RAG context size: 1159 chars

GEMINI (RAG) RESPONSE:

Gemini Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 53.78079104s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '53s'}]}}

COHERE (RAG) RESPONSE:

Candidate Summary:
This candidate has a strong background in semiconductor design verification, with a focus on RTL coding, verification, and development. They have worked in various roles, including Staff Design Verification Engineer, Technical Lead, and Senior Verification Engineer, gaining experience in both team leadership and individual contributions.

Matching Skills:
- RTL Coding and Verification: The candidate has extensive experience in RTL coding and verification, which is a key requirement for the role.
- SystemVerilog and UVM: Proficiency in SystemVerilog and UVM is evident from their resume, aligning with the job's expectations.
- Mixed-Signal Design Experience: Their work history includes mixed-signal designs, which is a plus for this position.
- Verification Methodology: The candidate has worked with VMM methodology and has experience in formality checking and analysis, which are valuable skills for the role.

Missing / Weak Areas:
- Lack of Specifics on SOC Verification: While the candidate has experience in RTL verification, the resume does not provide specific details on their SOC verification experience, which is a critical aspect of the job.
- Limited Exposure to Low-Power Design: The job description emphasizes low-power design and verification, but the candidate's resume does not highlight significant experience in this area.
- Missing Details on Verification Plans and Execution: The role requires a proven track record in developing and executing verification plans, but the resume lacks specific examples or achievements in this regard.

Suitability Score: 6/10

GROQ (RAG) RESPONSE:

Candidate Summary:
The candidate has around 8-10 years of experience in the field of semiconductor design verification, with a strong background in RTL coding, verification, and development. They have worked with various companies, including HCL Technologies, Renesas Design Vietnam Co., and Bos Semiconductors, and have experience with system control, clock structure, and verification methodologies such as VMM.

Matching Skills:
- Experience with RTL coding, verification, and development
- Familiarity with verification methodologies such as VMM
- Knowledge of AXI/AHB/APB protocols
- Experience with system control and clock structure
- Strong understanding of system verification, including STA, AC-timing, DFT-DRC, and synthesis
- Proficiency in languages such as English, SystemVerilog, and C/C++
- Experience with FPGA and verification automation

Missing / Weak Areas:
- The candidate's experience with SystemVerilog simulation and UVM is not explicitly mentioned, which is a crucial requirement for the job
- There is no clear indication of experience with low-power design and verification challenges, which is a highly desired skill for the position
- The candidate's experience with ARM processor-based designs and low-power design techniques is not explicitly mentioned
- No direct experience with design verification for IoT applications is mentioned

Suitability Score: 7/10
The candidate has a strong background in design verification and RTL development, but lacks some specific experience and skills required for the job, such as SystemVerilog simulation, UVM, and low-power design verification. With some additional training or experience, the candidate could be a strong fit for the position.

HUGGING FACE (RAG) RESPONSE:

Candidate Summary:
The candidate has around 8-10 years of experience in the field of semiconductor design verification, with a strong background in RTL coding, verification, and development. They have worked with various companies, including Bos Semiconductors, HCL Technologies, and Renesas Design Vietnam Co. Ltd., and have experience with system control, clock structure, and verification methodologies like VMM.

Matching Skills:
- Experience in design verification for digital and mixed-signal designs
- Familiarity with AXI/AHB/APB protocols
- Knowledge of verification methodologies like VMM
- Experience with RTL coding and verification
- Familiarity with system control and clock structure
- Strong understanding of electrical and electronics engineering (BSEE/MSEE degree equivalent)

Missing / Weak Areas:
- Limited experience with SystemVerilog and UVM, which are required for the job
- No explicit mention of experience with low-power design and verification challenges, or battery-operated designs
- No mention of experience with ARM processor-based designs, or C-based verification in an SOC environment
- Limited experience with gate-level simulations, FPGA, and post-silicon bring-up

Suitability Score: 6.5/10
The candidate has a strong background in design verification, but lacks experience in some specific areas required for the job, such as SystemVerilog, UVM, and low-power design verification. They also have limited experience with ARM processor-based designs and C-based verification in an SOC environment. However, their overall experience and skills in design verification make them a potential candidate for the role.

====================================================================================================
Candidate: 3.txt
RAG context size: 973 chars

GEMINI (RAG) RESPONSE:

Gemini Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 42.982967517s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '42s'}]}}

COHERE (RAG) RESPONSE:

Candidate Summary:
This candidate has experience in hardware verification and design, with a focus on automotive and semiconductor projects. They have worked on top-level chip verification, modeling, and design for HDR tone mapping algorithms. The candidate has also managed a team and has project management skills.

Matching Skills:
- Experience in hardware verification, including block-level and full-chip verification.
- Proficiency in SystemVerilog, UVM, and SystemC.
- Knowledge of computer architecture and low-power design considerations.
- Understanding of IP integration and mixed-signal designs.
- Familiarity with ARM-based designs and low-power techniques.
- Project management experience.

Missing / Weak Areas:
- The candidate's resume does not explicitly mention experience with security hardware, digital signal processors, or IoT applications, which are key aspects of the role.
- There is no mention of specific experience with AMBA AXI/AHB/APB, DMA, or power-gating techniques, which are required for the position.
- While the candidate has worked with SystemVerilog and SystemC, the job description also requires strong exposure to SystemVerilog simulation, which is not clearly evident.
- The resume lacks details on the candidate's involvement in creating test plans, testbench environments, and automation, which are crucial responsibilities for the role.

Suitability Score: 6/10

GROQ (RAG) RESPONSE:

Candidate Summary:
The candidate has around 5-6 years of experience in the field of semiconductor design verification, with a background in hardware verification engineering and experience in working with SystemVerilog, UVM, and C++. They have worked on various projects, including verifying top-level designs for automotive chip makers and developing virtual platforms for automotive ECUs.

Matching Skills:
- Experience with SystemVerilog, UVM, and C++
- Knowledge of AXI, AHB, and APB protocols
- Familiarity with verification of digital and mixed-signal designs
- Experience with hardware verification engineering and design verification
- Proficiency in programming languages such as Python and C++

Missing / Weak Areas:
- The candidate has less experience (5-6 years) than the ideal candidate (8-12 years) specified in the job description
- Limited experience in working with low-power design and verification challenges
- No explicit mention of experience with ARM processor-based designs, MIPS, or low-power design techniques
- No clear indication of experience with gate-level simulations, FPGA, or post-silicon bring-up

Suitability Score: 6.5/10
The candidate has some relevant technical skills and experience in design verification, but falls short in terms of the required years of experience and specific expertise in areas like low-power design and ARM processor-based designs. With additional training and experience, the candidate may be able to fill the gaps and become a stronger fit for the role.

HUGGING FACE (RAG) RESPONSE:

Candidate Summary:
The candidate has around 5-6 years of experience in hardware verification and design, with a background in electronic and communications engineering technology. They have worked on various projects, including hardware verification for a chip secure car access solution, modeling and verification for an HDR tone mapping algorithm, and developing a virtual platform for an automotive ECU.

Matching Skills:
- Experience with SystemVerilog and UVM
- Knowledge of verification methodologies, including testbench environment and scoreboarding
- Familiarity with SOC architecture, including AXI, AHB, and APB
- Experience with C++ and Python programming languages
- Background in ASIC and SOC design verification

Missing / Weak Areas:
- Lack of direct experience with mixed-signal designs and low-power design verification challenges
- Limited experience with gate-level simulations and post-silicon bring-up
- No explicit mention of experience with ARM processor-based designs, low-power design techniques, or MIPS architecture
- Insufficient information on experience with 3rd party IP/VIP integration and design verification for low-power battery-operated designs

Suitability Score: 6.5/10
The candidate has some relevant technical skills and experience in hardware verification, but lacks the desired level of experience in certain areas, such as mixed-signal designs, low-power design verification, and ARM processor-based designs. Additionally, the candidate's experience is slightly shorter than the 8-12 years required by the job description. However, they still demonstrate a strong foundation in verification methodologies and SOC architecture, making them a potential candidate for further consideration.

====================================================================================================
Candidate: 4.txt
RAG context size: 1187 chars

GEMINI (RAG) RESPONSE:

Gemini Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 32.496865506s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '32s'}]}}

COHERE (RAG) RESPONSE:

Candidate Summary:
The candidate is a Physical Design Engineer with over 5 years of experience in the semiconductor industry. They have worked on next-generation data center products and have a strong background in physical design implementation and verification.

Matching Skills:

### 36) Extract RAG scores

In [41]:
rag_score_rows = []

for item in rag_results:
    rag_score_rows.append({
        "candidate_name": item["candidate_name"],
        "gemini_rag_score": extract_score(item["gemini_output"]),
        "cohere_rag_score": extract_score(item["cohere_output"]),
        "groq_rag_score": extract_score(item["groq_output"]),
        "huggingface_rag_score": extract_score(item["huggingface_output"]),
        "openrouter_rag_score": extract_score(item["openrouter_output"]),
    })

rag_scores_df = pd.DataFrame(rag_score_rows)

rag_score_cols = ["gemini_rag_score", "cohere_rag_score", "groq_rag_score", "huggingface_rag_score", "openrouter_rag_score"]
rag_scores_df["rag_average_score"] = rag_scores_df[rag_score_cols].mean(axis=1, skipna=True)
rag_scores_df = rag_scores_df.sort_values(by="rag_average_score", ascending=False)

rag_scores_df

,candidate_name,gemini_rag_score,cohere_rag_score,groq_rag_score,huggingface_rag_score,rag_average_score
1,2 DV.txt,None,6.0,7.0,6.5,6.5
2,3.txt,None,6.0,6.5,6.5,6.333333
4,5.txt,None,6.0,4.0,NaN,5.0
3,4.txt,None,6.0,4.0,4.0,4.666667
0,1 DV.txt,None,6.0,2.0,2.0,3.333333

### 37) Compare RAG vs Non-RAG scores

This comparison shows whether RAG-enhanced retrieval produces different candidate rankings compared to the original full-text approach from Week 1-2.

In [42]:
comparison_df = scores_df[["candidate_name", "average_score"]].copy()
comparison_df = comparison_df.merge(
    rag_scores_df[["candidate_name", "rag_average_score"]],
    on="candidate_name"
)

comparison_df["score_difference"] = (
    comparison_df["rag_average_score"] - comparison_df["average_score"]
)
comparison_df = comparison_df.sort_values(by="rag_average_score", ascending=False)
comparison_df.columns = [
    "Candidate", "Non-RAG Avg Score", "RAG Avg Score", "Difference (RAG - Non-RAG)"
]

print("RAG vs Non-RAG Score Comparison:")
print(comparison_df.to_string(index=False))

RAG vs Non-RAG Score Comparison:
Candidate Non-RAG Avg Score RAG Avg Score Difference (RAG - Non-RAG)
 2 DV.txt          7.333333           6.5                  -0.833333
    3.txt          7.333333      6.333333                       -1.0
    5.txt          4.666667           5.0                   0.333333
    4.txt          4.333333      4.666667                   0.333333
 1 DV.txt               4.0      3.333333                  -0.666667

### 38) Final Recommendation (RAG-enhanced)

Using majority voting and average scoring from the RAG pipeline to produce the final recommended candidate.

In [43]:
from collections import Counter

rag_score_cols = ["gemini_rag_score", "cohere_rag_score", "groq_rag_score", "huggingface_rag_score", "openrouter_rag_score"]

rag_model_recommendations = {}
for col in rag_score_cols:
    valid = rag_scores_df.dropna(subset=[col])
    if not valid.empty:
        top = valid.sort_values(by=col, ascending=False).iloc[0]["candidate_name"]
        rag_model_recommendations[col] = top

print("RAG Top recommendation by each LLM:\n")
for model, candidate in rag_model_recommendations.items():
    print(f"  {model}: {candidate}")

votes = list(rag_model_recommendations.values())
vote_counter = Counter(votes)

print("\nMajority vote result:\n")
for candidate, count in vote_counter.items():
    print(f"  {candidate}: {count} vote(s)")

majority_best = vote_counter.most_common(1)[0][0]
best_avg = rag_scores_df.iloc[0]["candidate_name"]

# Tiebreaker 1: majority vote
if majority_best == best_avg:
    final_candidate = majority_best
    reason = "Majority vote and average score agree"
else:
    # Tiebreaker 2: average score
    top_score = rag_scores_df.iloc[0]["rag_average_score"]
    second_score = rag_scores_df.iloc[1]["rag_average_score"]
    if top_score != second_score:
        final_candidate = best_avg
        reason = "Tie in majority vote — decided by higher average score"
    else:
        # Tiebreaker 3: Borda count
        # Each model ranks all candidates. Points awarded by position.
        # 1st = N points, 2nd = N-1 points, etc.
        # Candidate with most total points wins.
        rank_points = {}
        for col in rag_score_cols:
            valid = rag_scores_df.dropna(subset=[col])
            ranked = valid.sort_values(by=col, ascending=False).reset_index(drop=True)
            for rank, row in ranked.iterrows():
                name = row["candidate_name"]
                points = len(ranked) - rank
                rank_points[name] = rank_points.get(name, 0) + points
        final_candidate = max(rank_points, key=rank_points.get)
        reason = "Average scores tied — decided by Borda count (cumulative rank points)"

print(f"\nTiebreaker reason: {reason}")
print("\n" + "=" * 60)
print(f"FINAL RECOMMENDED CANDIDATE (RAG-enhanced): {final_candidate}")
print("=" * 60)

RAG Top recommendation by each LLM:

  cohere_rag_score: 2 DV.txt
  groq_rag_score: 2 DV.txt
  huggingface_rag_score: 2 DV.txt

Majority vote result:

  2 DV.txt: 3 vote(s)

============================================================
FINAL RECOMMENDED CANDIDATE (RAG-enhanced): 2 DV.txt
============================================================

### 39) Summary: What RAG adds to the pipeline

In [44]:
summary = """
RAG PIPELINE SUMMARY
====================

Week 1-2 (Baseline):
  - Full resume text sent directly to LLM
  - No semantic retrieval
  - LLM sees all text including irrelevant sections

Week 3 (RAG - chunk size 500, overlap 100):
  - Resumes split into chunks and embedded using all-MiniLM-L6-v2
  - FAISS vector store for fast semantic similarity search
  - Top-3 most relevant chunks retrieved per candidate

Week 4 (RAG Refined - chunk size 300, overlap 80, top-4 chunks):
  - Smaller chunks = more granular, precise retrieval
  - Retrieves top-4 chunks instead of top-3
  - More focused context passed to LLM

Benefits of RAG over Baseline:
  1. Reduces token usage with shorter, more focused prompts
  2. Focuses LLM on the most relevant parts of a resume
  3. Enables semantic matching beyond simple keyword matching
  4. Scales better when resumes are long

Stack used:
  - LangChain: Document objects, RecursiveCharacterTextSplitter, RetrievalQA chain
  - FAISS: vector similarity search
  - sentence-transformers/all-MiniLM-L6-v2: embedding model
  - Gemini / Cohere / Groq / HuggingFace: LLM evaluation
"""
print(summary)

RAG PIPELINE SUMMARY
====================

Week 1-2 (Baseline):
  - Full resume text sent directly to LLM
  - No semantic retrieval
  - LLM sees all text including irrelevant sections

Week 3 (RAG - chunk size 500, overlap 100):
  - Resumes split into chunks and embedded using all-MiniLM-L6-v2
  - FAISS vector store for fast semantic similarity search
  - Top-3 most relevant chunks retrieved per candidate

Week 4 (RAG Refined - chunk size 300, overlap 80, top-4 chunks):
  - Smaller chunks = more granular, precise retrieval
  - Retrieves top-4 chunks instead of top-3
  - More focused context passed to LLM

Benefits of RAG over Baseline:
  1. Reduces token usage with shorter, more focused prompts
  2. Focuses LLM on the most relevant parts of a resume
  3. Enables semantic matching beyond simple keyword matching
  4. Scales better when resumes are long

Stack used:
  - LangChain: Document objects, RecursiveCharacterTextSplitter, RetrievalQA chain
  - FAISS: vector similarity search
  - sentence-transformers/all-MiniLM-L6-v2: embedding model
  - Gemini / Cohere / Groq / HuggingFace: LLM evaluation

---
## LangChain RetrievalQA Chain

This is the proper LangChain usage — a `RetrievalQA` chain that links the FAISS retriever directly to an LLM in one pipeline. LangChain handles the retrieval, prompt formatting, and LLM call automatically.

In [52]:
!pip install -q langchain-groq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.5/137.5 kB 7.5 MB/s eta 0:00:00

In [53]:
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from langchain_groq import ChatGroq

# Install langchain-groq if needed
import subprocess
subprocess.run(["pip", "install", "-q", "langchain-groq"], capture_output=True)

from langchain_groq import ChatGroq

# LangChain prompt template
langchain_prompt_template = ChatPromptTemplate.from_template("""
You are an HR screening assistant.
Use the following resume sections to evaluate the candidate.

Resume Sections:
{context}

Job Description Query:
{question}

Evaluate the candidate and provide:
Candidate Summary:
Matching Skills:
Missing / Weak Areas:
Suitability Score (out of 10):
""")

# Use Groq as the LangChain LLM - same API key you already have
langchain_llm = ChatGroq(
    api_key=GROQ_API_KEY,
    model_name="llama-3.3-70b-versatile"
)

# Helper to format retrieved docs into a single string
def format_docs(docs):
    return "\n\n".join([doc.page_content for doc in docs])

# Build LangChain LCEL pipeline
retriever = refined_vectorstore.as_retriever(search_kwargs={"k": 4})

langchain_pipeline = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | langchain_prompt_template
    | langchain_llm
    | StrOutputParser()
)

# Run through the full LangChain pipeline
print("Running LangChain LCEL pipeline...\n")
langchain_result = langchain_pipeline.invoke(cleaned_job_description[:500])

print("LangChain Result:\n")
print(langchain_result)

Running LangChain LCEL pipeline...

LangChain Result:

**Candidate Summary:**
The candidate is an experienced design verification engineer with a strong background in semiconductor design verification, having worked in various companies such as Skyechip Sdn Bhd, HCL Technologies, and Renesas Design Vietnam Co. They have a solid educational foundation, graduating from the University of Malaysia Perlis (UniMAP) with a major in a relevant field. The candidate has around 9-10 years of experience in the field, with expertise in RTL coding, verification, and development.

**Matching Skills:**
The candidate's skills match the job requirements in the following areas:
* Design verification experience (around 9-10 years)
* RTL coding, verification, and development expertise
* Familiarity with VMM methodology, RTL/SDF simulation, formalilty checking/analyzing, DFT-DRC, and STA AC-timing
* Knowledge of AXI, AHB, and APB protocols
* Strong technical skills in languages such as English, with limited proficiency in Mandarin and native/bilingual proficiency in Malay

**Missing / Weak Areas:**
The candidate may have some gaps in the following areas:
* The job requires 8-12 years of experience, and while the candidate has around 9-10 years of experience, it may not be exactly within the desired range.
* There is no explicit mention of experience in developing and executing verification plans for complex SoC designs, which is a key responsibility of the job.
* The candidate's experience is mostly in Asian locations (Malaysia, Vietnam), and it is unclear if they have experience working in the US or with US-based companies.

**Suitability Score:**
Based on the evaluation, I would give the candidate a suitability score of 8 out of 10. The candidate has a strong technical background and relevant experience in design verification, which aligns with the job requirements. However, there may be some gaps in terms of exact experience and geographic location. Overall, the candidate is a strong contender for the position, but may require some additional evaluation or interview to confirm their fit.

---
# Analysis & Conclusions

### LLM Comparison Table

A summary of all 4 LLMs used in this project, comparing their characteristics to justify why each was selected.

In [54]:
llm_comparison = {
    "Model": [
        "Gemini 2.5 Flash",
        "Cohere Command-R",
        "Groq (Llama 3.3 70B)",
        "HuggingFace (Qwen2.5-72B)",
        "OpenRouter (DeepSeek R1)"
    ],
    "Provider": ["Google", "Cohere", "Meta", "Alibaba", "DeepSeek"],
    "Accessed Via": ["Gemini API", "Cohere API", "Groq API", "HuggingFace API", "OpenRouter API"],
    "Strengths": [
        "Strong reasoning, fast, multimodal",
        "Enterprise NLP, low hallucination",
        "Extremely fast inference",
        "Strong multilingual and reasoning",
        "State-of-the-art reasoning model"
    ],
    "Free Tier": ["Yes", "Yes", "Yes", "Yes", "Yes"],
}

llm_df = pd.DataFrame(llm_comparison)
print("LLM Comparison Table:")
print(llm_df.to_string(index=False))
print()
print("5 APIs selected from 5 completely different providers and model families.")
print("Odd number (5) ensures majority vote always produces a clear winner.")
print("Local models (e.g. Ollama) were considered but ruled out as they require")
print("a persistent local server incompatible with Google Colab.")

LLM Comparison Table:
                      Model             Provider                                            Strengths Free Tier                               Best For
           Gemini 2.5 Flash               Google                   Strong reasoning, fast, multimodal       Yes      General reasoning & summarisation
           Cohere Command-R               Cohere Enterprise NLP, retrieval-focused, low hallucination       Yes Document comparison & enterprise tasks
       Groq (Llama 3.3 70B)                 Groq   Extremely fast inference, strong open-source model       Yes               Speed-critical NLP tasks
HuggingFace (Llama 3.1 70B) Meta via HuggingFace            Open-source, widely benchmarked, flexible       Yes            Open-source reproducibility

### Example of Retrieved Chunks

This shows exactly what the RAG system retrieves for a candidate — demonstrating that only the most relevant resume sections are passed to the LLM rather than the entire document.

In [55]:
print("=" * 70)
print("EXAMPLE: What RAG retrieves for a candidate")
print("=" * 70)

example_candidate = list(cleaned_resumes.keys())[0]
example_chunks = get_rag_context_refined(example_candidate, cleaned_job_description[:500])

print(f"Candidate: {example_candidate}")
print(f"Full resume length: {len(cleaned_resumes[example_candidate])} chars")
print(f"RAG context length: {len(example_chunks)} chars")
print(f"Token reduction: ~{round((1 - len(example_chunks)/len(cleaned_resumes[example_candidate]))*100)}%")
print()
print("Retrieved chunks (what the LLM actually sees):")
print("-" * 70)
print(example_chunks)
print("-" * 70)
print()
print("Why this matters:")
print("  The LLM only evaluates the most job-relevant sections of the resume.")
print("  Irrelevant roles, personal details, and unrelated skills are excluded.")
print("  This leads to a more accurate and fair evaluation of each candidate.")

======================================================================
EXAMPLE: What RAG retrieves for a candidate
======================================================================
Candidate: 1 DV.txt
Full resume length: 2883 chars
RAG context length: 1150 chars
Token reduction: ~60%

Retrieved chunks (what the LLM actually sees):
----------------------------------------------------------------------
top skills axi apb chi languages english native or bilingual mandarin limited working malay native or bilingual design verification engineer kulim kedah malaysia summary currently working as design verification engineer at skyechip sdn bhd graduated from university of malaysia perlis unimap majoring

skyechip sdn bhd graduated from university of malaysia perlis unimap majoring in microelectronic engineering. experience skyechip design verification engineer august 2022-present 1 year 4 months penang malaysia fuji electric m sdn bhd manufacturing engineer april 2022-august 2022 5 months kulim

dielectric workshop spare parts and subfab - able to work in cleanroom education universiti malaysia perlis bachelor of engineering - be microelectronic engineering politeknik tuanku sultanah bahiyah diploma electronic engineering computer page 3 of 3

on the new machine - run troubleshoot service and repair linked machine page 2 of 3 - ensure low tools downtime - perform periodic maintenance - participate with engineer improvement projects silterra malaysia sdn. bhd. equipment technician december 2016-october 2017 11 months kulim kedah malaysia
----------------------------------------------------------------------

Why this matters:
  The LLM only evaluates the most job-relevant sections of the resume.
  Irrelevant roles, personal details, and unrelated skills are excluded.
  This leads to a more accurate and fair evaluation of each candidate.

### Written Conclusion: Did RAG Improve Results?

Analysis of whether RAG-enhanced retrieval produced better or different candidate rankings compared to the full-text baseline.

In [56]:
print("CONCLUSION: RAG vs Non-RAG Analysis")
print("=" * 60)
print()

# Get both final candidates
non_rag_best = scores_df.iloc[0]["candidate_name"]
rag_best = rag_scores_df.iloc[0]["candidate_name"]

non_rag_top_score = scores_df.iloc[0]["average_score"]
rag_top_score = rag_scores_df.iloc[0]["rag_average_score"]

print(f"Non-RAG top candidate : {non_rag_best} (avg score: {non_rag_top_score:.2f})")
print(f"RAG top candidate     : {rag_best} (avg score: {rag_top_score:.2f})")
print()

if non_rag_best == rag_best:
    print("FINDING: Both pipelines agree on the top candidate.")
    print("This suggests the ranking is stable and reliable across methods.")
    print("RAG confirms the non-RAG result with more focused evidence.")
else:
    print("FINDING: RAG and Non-RAG pipelines recommend different candidates.")
    print("This suggests the full resume contained noise that affected Non-RAG scoring.")
    print("RAG is likely more accurate as it focuses on job-relevant sections only.")

print()
print("Overall RAG benefits observed:")
print("  1. Prompt size reduced — LLM receives only relevant resume sections")
print("  2. Semantic retrieval — chunks matched by meaning, not just keywords")
print("  3. More consistent scores across models when context is focused")

CONCLUSION: RAG vs Non-RAG Analysis
============================================================

Non-RAG top candidate : 2 DV.txt (avg score: 7.33)
RAG top candidate     : 2 DV.txt (avg score: 6.50)

FINDING: Both pipelines agree on the top candidate.
This suggests the ranking is stable and reliable across methods.
RAG confirms the non-RAG result with more focused evidence.

Overall RAG benefits observed:
  1. Prompt size reduced — LLM receives only relevant resume sections
  2. Semantic retrieval — chunks matched by meaning, not just keywords
  3. More consistent scores across models when context is focused

### Final Statement: Best Model and Pipeline

In [57]:
print("FINAL STATEMENT: Best Model and Pipeline")
print("=" * 60)
print()

# Find which model was most consistent (least variance in scores)
rag_score_cols = ["gemini_rag_score", "cohere_rag_score", "groq_rag_score", "huggingface_rag_score"]
variances = rag_scores_df[rag_score_cols].var()
most_consistent_model = variances.idxmin()
most_decisive_model = variances.idxmax()

print(f"Most consistent model (lowest score variance) : {most_consistent_model}")
print(f"Most decisive model   (highest score variance): {most_decisive_model}")
print()

final_best = rag_scores_df.iloc[0]["candidate_name"]
print(f"Final recommended candidate: {final_best}")
print()
print("Best overall pipeline: RAG-enhanced (Week 4, chunk_size=300)")
print("Reasoning:")
print("  - Smaller chunks provide more precise semantic retrieval")
print("  - Top-4 retrieval gives broader coverage than top-3")
print("  - Multi-model ensemble with average scoring reduces single-model bias")
print("  - Majority voting provides a transparent, explainable final decision")

FINAL STATEMENT: Best Model and Pipeline
============================================================

Most consistent model (lowest score variance) : cohere_rag_score
Most decisive model   (highest score variance): huggingface_rag_score

Final recommended candidate: 2 DV.txt

Best overall pipeline: RAG-enhanced (Week 4, chunk_size=300)
Reasoning:
  - Smaller chunks provide more precise semantic retrieval
  - Top-4 retrieval gives broader coverage than top-3
  - Multi-model ensemble with average scoring reduces single-model bias
  - Majority voting provides a transparent, explainable final decision

### Future Enhancements

Two key enhancements that would significantly improve this system beyond the current scope.

In [58]:
print("FUTURE ENHANCEMENT 1: Web-Based UI Upload System")
print("-" * 60)
print("""
Currently the system runs in Google Colab and requires manual file uploads.
A web-based UI would allow:
  - Recruiters to upload CVs and job descriptions via a browser
  - Real-time screening results displayed on screen
  - No coding knowledge required to use the system

Proposed stack: Streamlit or Gradio (Python-based, fast to build)
  - Streamlit: file_uploader widget for CVs and job description PDF
  - Results shown as interactive tables and score charts
  - One-click deployment to Streamlit Cloud (free hosting)

This directly addresses the Week 7-8 milestone of building a UI.
""")

print("FUTURE ENHANCEMENT 2: Bias and Fairness Checking")
print("-" * 60)
print("""
Current limitation: LLMs may introduce bias based on names, locations,
or universities mentioned in the resume.

Proposed solution:
  - Anonymise resumes before screening (remove names, gender indicators,
    nationality, age, photo references) using a pre-processing step
  - Compare scores before and after anonymisation to measure bias
  - Flag candidates where score changed significantly after anonymisation

This improves fairness and makes the system more suitable for real-world
HR deployment where anti-discrimination compliance is required.
""")

FUTURE ENHANCEMENT 1: Web-Based UI Upload System
------------------------------------------------------------

Currently the system runs in Google Colab and requires manual file uploads.
A web-based UI would allow:
  - Recruiters to upload CVs and job descriptions via a browser
  - Real-time screening results displayed on screen
  - No coding knowledge required to use the system

Proposed stack: Streamlit or Gradio (Python-based, fast to build)
  - Streamlit: file_uploader widget for CVs and job description PDF
  - Results shown as interactive tables and score charts
  - One-click deployment to Streamlit Cloud (free hosting)

This directly addresses the Week 7-8 milestone of building a UI.

FUTURE ENHANCEMENT 2: Bias and Fairness Checking
------------------------------------------------------------

Current limitation: LLMs may introduce bias based on names, locations,
or universities mentioned in the resume.

Proposed solution:
  - Anonymise resumes before screening (remove names, gender indicators,
    nationality, age, photo references) using a pre-processing step
  - Compare scores before and after anonymisation to measure bias
  - Flag candidates where score changed significantly after anonymisation

This improves fairness and makes the system more suitable for real-world
HR deployment where anti-discrimination compliance is required.