1) Install libraries

In [1]:
!pip install -q -U pypdf pandas google-genai cohere groq huggingface_hub

2) Import Libraries

In [2]:
import os
import re
import json
import zipfile
from pathlib import Path
from getpass import getpass

import pandas as pd
from pypdf import PdfReader

from google.colab import files

from google import genai
import cohere
from groq import Groq
from huggingface_hub import InferenceClient

3) upload zip file

In [3]:
uploaded = files.upload()

Saving FTSP (Week 1)  .zip to FTSP (Week 1)   (1).zip

4) extract zip file

In [4]:
extract_folder = Path("project_files")
extract_folder.mkdir(exist_ok=True)

zip_filename = list(uploaded.keys())[0]

with zipfile.ZipFile(zip_filename, "r") as zip_ref:
    zip_ref.extractall(extract_folder)

print("Files extracted successfully.\n")

for file in sorted(extract_folder.iterdir()):
    print(file.name)

Files extracted successfully.

1 DV.txt
2 DV.txt
3.txt
4.txt
5.txt
Sr. Staff Engineer, Design Verification.pdf

5) Locate resumes and job description

In [5]:
txt_files = sorted(extract_folder.glob("*.txt"))
pdf_files = sorted(extract_folder.glob("*.pdf"))

print("Resume files found:")
for f in txt_files:
    print("-", f.name)

print("\nPDF files found:")
for f in pdf_files:
    print("-", f.name)

if len(pdf_files) == 0:
    raise FileNotFoundError("No PDF job description found in the extracted folder.")

Resume files found:
- 1 DV.txt
- 2 DV.txt
- 3.txt
- 4.txt
- 5.txt

PDF files found:
- Sr. Staff Engineer, Design Verification.pdf

6) Read all text files

In [6]:
def read_text_file(file_path):
    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
        return f.read()

raw_resumes = {}
for file_path in txt_files:
    raw_resumes[file_path.name] = read_text_file(file_path)

print("Loaded resumes:", len(raw_resumes))
print("\nSample preview:\n")

for name, text in raw_resumes.items():
    print("=" * 80)
    print(name)
    print(text[:500])
    print()

Loaded resumes: 5

Sample preview:

================================================================================
1 DV.txt

Top Skills
AXI
APB
CHI
Languages
English  (Native or Bilingual)
Mandarin  (Limited Working)
Malay  (Native or Bilingual)
Design Verification Engineer
Kulim, Kedah, Malaysia
Summary
Currently working as Design Verification Engineer at Skyechip Sdn
Bhd
Graduated from University of Malaysia Perlis (UniMAP), majoring in
Microelectronic Engineering.
Experience
SkyeChip
Design Verification Engineer
August 2022-Present (1 year 4 months)
Penang, Malaysia
Fuji Electric (M) Sdn Bhd
Manufacturing Engin

================================================================================
2 DV.txt

Top Skills
RTL Coding
RTL Verification
RTL Development
Languages
English
Staff Design Verification
Ho Chi Minh City Metropolitan Area
Experience
BOS Semiconductors
Staff Design Verification Engineer
December 2022-Present (1 year)
HCL Technologies
Technical Lead
March 2022-December 2022 (10 months)
RTL design for clock controller, power control, clock and power hardmacro
integration.
Integration system control block in cpu sub-system.
RTL verification system control.
Clock structure, SDC for sy

================================================================================
3.txt

Principales comptences
C++
Verilog
FPGA
Languages
English  (Limited Working)
Design Verification Leader
Vit Nam
Exprience
CoAsia SEMI Vietnam Co., Ltd
RTL Design Verification Leader
octobre 2020-Present (3 ans 2 mois)
Hanoi, Hanoi, Vietnam
#Verification #RTLDesign #UVM #SystemVerilog #ASIC #SOC #LPDDR4/5
#NoC #IWB #VIP
FPT Software
Hardware Engineer - FPT Global Automative - LSI division
aot 2015-septembre 2020 (5 ans 2 mois)
Hoa Lac Hi-Tech Park
.Apr 2019 - Sept 2020: Hardware Verification En

================================================================================
4.txt

Top Skills
C
C++
Java
Languages
Malay  (Professional Working)
English  (Full Professional)
Chinese (Simplified)  (Native or
Bilingual)
Honors-Awards
UNMC High Achievers' Scholarship
Best Society Award 2016/17
Physical Design Engineer at Intel Corporation
Kulim, Kedah, Malaysia
Summary
Currently working on an Intel's product of the latest technology.
Building in-depth fundamental technical understandings with hands-
on experiences
Experience
Intel Corporation
Physical Design Engineer
August 20

================================================================================
5.txt

Top Skills
Very-Large-Scale Integration (VLSI)
System on a Chip (SoC)
Innovus
Physical design engineer with various experiences in VLSI
Singapore
Summary
Experienced Semiconductor Engineer specializing in Backend digital
design who spent his early career of 4 years in Intel and learned
most of the clock architecture and planning for CPU design. I have
experience in designing clock mesh with spice simulation and top
clock distribution with specially designed strong buffers. On top of
that, I wa

7) Read the job description PDF

In [7]:
def read_pdf_text(pdf_path):
    reader = PdfReader(str(pdf_path))
    text = []
    for page in reader.pages:
        page_text = page.extract_text()
        if page_text:
            text.append(page_text)
    return "\n".join(text)

job_pdf_path = pdf_files[0]
raw_job_description = read_pdf_text(job_pdf_path)

print("Job description file:", job_pdf_path.name)
print("\nPreview:\n")
print(raw_job_description[:1500])

Job description file: Sr. Staff Engineer, Design Verification.pdf

Preview:

Sr. Staff Engineer, Design Verification

Staff Engineer – Design Verification

Client is looking for an experienced Staff Design Verification Engineer to join our dynamic team in
Austin, TX. The ideal candidate will have 8-12 years of experience in the field of semiconductor
design verification, and a proven track record of success in developing and executing verification
plans for complex SoC designs.

Responsibilities:

The Design Verification Engineer will be responsible for verification of digital and mixed-signal
designs, including systems-on-chip with multiple CPUs, and digital signal processors, security
hardware, and other logic for IoT applications.

Specific Responsibilities:
• Ideal candidate should have demonstrated successful design verification tasks at block, sub-
system, and full-chip level.
• Must have participated in all phases of chip development, from creating test plans, creating
testbench environment (SV/UVM), integrate VIP’s, automate test env for randomized testing
and score boarding.
• Utilize UVM to create drivers, monitors, predictors, and scoreboards.
• In-Depth knowledge of SoC architecture with AMBA AXI/AHB/APB, DMA’s, Security, clock,
and power-gating techniques is required.
• Responsible for verification of block(s) that includes writing tests, assertion and coverage for
a block.
• Create tests to achieve coverage goals while verifying functionality.
• Develop support utilities for verification automation, test bench a

8) Text preprocessing

In [8]:
def preprocess_text(text):
    if not isinstance(text, str):
        text = str(text)

    # normalize line breaks / spaces
    text = text.replace("\xa0", " ")
    text = text.replace("\n", " ")
    text = text.replace("\t", " ")

    # lowercase
    text = text.lower()

    # remove phone numbers
    text = re.sub(r'(\+?\d[\d\-\(\) ]{7,}\d)', ' ', text)

    # remove repeated punctuation-like noise but keep useful technical symbols
    # keep letters, digits, spaces, slash, plus, hash, hyphen, dot
    text = re.sub(r'[^a-z0-9/\+\#\-\.\s]', ' ', text)

    # remove multiple dots or dashes if noisy
    text = re.sub(r'[\.]{2,}', ' ', text)
    text = re.sub(r'[-]{2,}', ' ', text)

    # collapse spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

9) Apply preprocessing to resumes and job description

In [9]:
cleaned_resumes = {}
for name, text in raw_resumes.items():
    cleaned_resumes[name] = preprocess_text(text)

cleaned_job_description = preprocess_text(raw_job_description)

print("Cleaned job description preview:\n")
print(cleaned_job_description[:1200])

print("\n\nCleaned resume preview:\n")
for name, text in cleaned_resumes.items():
    print("=" * 80)
    print(name)
    print(text[:400])
    print()

Cleaned job description preview:

sr. staff engineer design verification staff engineer design verification client is looking for an experienced staff design verification engineer to join our dynamic team in austin tx. the ideal candidate will have 8-12 years of experience in the field of semiconductor design verification and a proven track record of success in developing and executing verification plans for complex soc designs. responsibilities the design verification engineer will be responsible for verification of digital and mixed-signal designs including systems-on-chip with multiple cpus and digital signal processors security hardware and other logic for iot applications. specific responsibilities ideal candidate should have demonstrated successful design verification tasks at block sub- system and full-chip level. must have participated in all phases of chip development from creating test plans creating testbench environment sv/uvm integrate vip s automate test env for randomized testing and score boarding. utilize uvm to create drivers monitors predictors and scoreboards. in-depth knowledge of soc architecture with amba axi/ahb/apb dma s security clock and power-gating techniques is required. responsible fo


Cleaned resume preview:

================================================================================
1 DV.txt
top skills axi apb chi languages english native or bilingual mandarin limited working malay native or bilingual design verification engineer kulim kedah malaysia summary currently working as design verification engineer at skyechip sdn bhd graduated from university of malaysia perlis unimap majoring in microelectronic engineering. experience skyechip design verification engineer august 2022-presen

================================================================================
2 DV.txt
top skills rtl coding rtl verification rtl development languages english staff design verification ho chi minh city metropolitan area experience bos semiconductors staff design verification engineer december 2022-present 1 year hcl technologies technical lead march 2022-december 2022 10 months rtl design for clock controller power control clock and power hardmacro integration. integration system c

================================================================================
3.txt
principales comptences c++ verilog fpga languages english limited working design verification leader vit nam exprience coasia semi vietnam co. ltd rtl design verification leader octobre 2020-present 3 ans 2 mois hanoi hanoi vietnam #verification #rtldesign #uvm #systemverilog #asic #soc #lpddr4/5 #noc #iwb #vip fpt software hardware engineer - fpt global automative - lsi division aot 2015-septembr

================================================================================
4.txt
top skills c c++ java languages malay professional working english full professional chinese simplified native or bilingual honors-awards unmc high achievers scholarship best society award 2016/17 physical design engineer at intel corporation kulim kedah malaysia summary currently working on an intel s product of the latest technology. building in-depth fundamental technical understandings with ha

================================================================================
5.txt
top skills very-large-scale integration vlsi system on a chip soc innovus physical design engineer with various experiences in vlsi singapore summary experienced semiconductor engineer specializing in backend digital design who spent his early career of 4 years in intel and learned most of the clock architecture and planning for cpu design. i have experience in designing clock mesh with spice simu

10) Save cleaned text files

In [10]:
cleaned_folder = Path("cleaned_texts")
cleaned_folder.mkdir(exist_ok=True)

for name, text in cleaned_resumes.items():
    out_path = cleaned_folder / f"cleaned_{name}"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)

with open(cleaned_folder / "cleaned_job_description.txt", "w", encoding="utf-8") as f:
    f.write(cleaned_job_description)

print("Cleaned files saved in:", cleaned_folder)
print("\nSaved files:")
for f in sorted(cleaned_folder.iterdir()):
    print("-", f.name)

Cleaned files saved in: cleaned_texts

Saved files:
- cleaned_1 DV.txt
- cleaned_2 DV.txt
- cleaned_3.txt
- cleaned_4.txt
- cleaned_5.txt
- cleaned_job_description.txt

11) preprocessing summary table

In [11]:
summary_rows = []

for name in raw_resumes:
    raw_text = raw_resumes[name]
    cleaned_text = cleaned_resumes[name]

    summary_rows.append({
        "file_name": name,
        "raw_char_count": len(raw_text),
        "cleaned_char_count": len(cleaned_text),
        "removed_chars": len(raw_text) - len(cleaned_text)
    })

summary_rows.append({
    "file_name": "job_description_pdf",
    "raw_char_count": len(raw_job_description),
    "cleaned_char_count": len(cleaned_job_description),
    "removed_chars": len(raw_job_description) - len(cleaned_job_description)
})

summary_df = pd.DataFrame(summary_rows)
summary_df

             file_name  raw_char_count  cleaned_char_count  removed_chars
0             1 DV.txt            2974                2883             91
1             2 DV.txt            1403                1362             41
2                3.txt            1699                1646             53
3                4.txt            4800                4692            108
4                5.txt            4376                4215            161
5  job_description_pdf            2562                2422            140

12) Create prompts

In [12]:
SYSTEM_PROMPT = """
You are an HR screening assistant.
Your task is to compare a candidate's resume with a job description.

Focus on:
1. Relevant technical skills
2. Relevant work experience
3. Overall suitability for the role

Return the answer in a clear and concise format with:
- Candidate Summary
- Matching Skills
- Missing / Weak Areas
- Suitability Score out of 10
"""

In [13]:
def build_user_prompt(job_description, candidate_name, resume_text):
    return f"""
Job Description:
{job_description}

Candidate Resume File Name:
{candidate_name}

Candidate Resume Text:
{resume_text}

Please evaluate this candidate against the job description.

Format your answer as:
Candidate Summary:
Matching Skills:
Missing / Weak Areas:
Suitability Score:
"""

13) Enter API keys

In [14]:
COHERE_API_KEY = getpass("Enter your Cohere API key: ")
GEMINI_API_KEY = getpass("Enter your Gemini API key: ")
GROQ_API_KEY = getpass("Enter your Groq API key: ")
HF_API_KEY = getpass("Enter your Hugging Face API key: ")

Enter your Cohere API key: ··········
Enter your Gemini API key: ··········
Enter your Groq API key: ··········
Enter your Hugging Face API key: ··········

14) Set up API clients

In [15]:
# Gemini client
gemini_client = genai.Client(api_key=GEMINI_API_KEY)

# Cohere client
co = cohere.ClientV2(api_key=COHERE_API_KEY)

# Groq client
groq_client = Groq(api_key=GROQ_API_KEY)

# Hugging Face client
hf_client = InferenceClient(api_key=HF_API_KEY)

15) Gemini response function

In [16]:
def get_gemini_response(system_prompt, user_prompt, model_name="gemini-2.5-flash"):
    full_prompt = f"System Prompt:\n{system_prompt}\n\nUser Prompt:\n{user_prompt}"

    response = gemini_client.models.generate_content(
        model=model_name,
        contents=full_prompt
    )

    return response.text

16) Cohere response function

In [17]:
def get_cohere_response(system_prompt, user_prompt, model_name="command-r-08-2024"):
    response = co.chat(
        model=model_name,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]
    )

    # Cohere V2 responses may return content blocks
    if hasattr(response, "message") and hasattr(response.message, "content"):
        parts = []
        for item in response.message.content:
            if hasattr(item, "text"):
                parts.append(item.text)
            elif isinstance(item, dict) and "text" in item:
                parts.append(item["text"])
        return "\n".join(parts).strip()

    return str(response)

17. Grok Function

In [18]:
def get_groq_response(system_prompt, user_prompt, model_name="llama-3.3-70b-versatile"):
    response = groq_client.chat.completions.create(
        model=model_name,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]
    )
    return response.choices[0].message.content

18. HuggingFace Function

In [19]:
def get_huggingface_response(
    system_prompt,
    user_prompt,
    model_name="meta-llama/Llama-3.1-70B-Instruct"
):
    response = hf_client.chat.completions.create(
        model=model_name,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        max_tokens=800
    )
    return response.choices[0].message.content

19) Test one resume first

In [20]:
test_candidate = list(cleaned_resumes.keys())[0]
test_resume = cleaned_resumes[test_candidate]

test_prompt = build_user_prompt(
    job_description=cleaned_job_description,
    candidate_name=test_candidate,
    resume_text=test_resume
)

print("Testing candidate:", test_candidate)

print("\n--- GEMINI OUTPUT ---\n")
try:
    print(get_gemini_response(SYSTEM_PROMPT, test_prompt))
except Exception as e:
    print("Gemini Error:", e)

print("\n--- COHERE OUTPUT ---\n")
try:
    print(get_cohere_response(SYSTEM_PROMPT, test_prompt))
except Exception as e:
    print("Cohere Error:", e)

print("\n--- GROQ OUTPUT ---\n")
try:
    print(get_groq_response(SYSTEM_PROMPT, test_prompt))
except Exception as e:
    print("Groq Error:", e)

print("\n--- HUGGING FACE OUTPUT ---\n")
try:
    print(get_huggingface_response(SYSTEM_PROMPT, test_prompt))
except Exception as e:
    print("Hugging Face Error:", e)

Testing candidate: 1 DV.txt

--- GEMINI OUTPUT ---

**Candidate Summary:**
The candidate holds a Bachelor's degree in Microelectronic Engineering and has 1 year 4 months of experience as a Design Verification Engineer. Their "top skills" list AXI, APB, and CHI. Prior to their current DV role, their experience primarily consists of manufacturing, equipment maintenance, and various non-technical positions.

**Matching Skills:**
*   **Education:** Possesses a Bachelor of Engineering in Microelectronic Engineering, aligning with the BSEE/MSEE requirement.
*   **Architectural Knowledge (Partial):** Lists AXI, APB, and CHI as top skills, demonstrating some familiarity with AMBA protocols relevant to SoC architecture.

**Missing / Weak Areas:**
*   **Experience Gap:** Critically falls short of the required 8-12 years of experience in semiconductor design verification, having only 1 year 4 months of direct DV experience.
*   **Lack of Specific DV Expertise:** The resume provides no details on essential DV responsibilities such as creating test plans, developing SV/UVM testbench environments, integrating VIPs, randomized testing, scoreboarding, writing drivers/monitors/predictors, assertion-based verification, coverage analysis, gate-level simulations, FPGA/post-silicon bring-up, mixed-signal verification, C-based verification, or low-power design verification challenges.
*   **Missing Language Proficiency:** Does not list proficiency in SystemVerilog, UVM, Verilog, C/C++, Python, or Makefiles, all of which are explicitly required.
*   **No Proven Track Record:** Due to the limited duration and lack of specific details in their DV experience, there is no evidence of a "proven track record of success in developing and executing verification plans for complex SoC designs" as required for a Sr. Staff role.
*   **Overall Suitability for Seniority:** The candidate's experience level and lack of demonstrated technical depth are far below the expectations for a Sr. Staff Engineer position.

**Suitability Score:** 1/10

--- COHERE OUTPUT ---

Candidate Summary:
This candidate is a Design Verification Engineer with a background in microelectronic engineering. They have experience in the semiconductor industry and have worked on various projects, including design verification, equipment engineering, and manufacturing. The candidate's resume highlights their skills in process quality control, continuous improvement, and equipment maintenance.

Matching Skills:
- Experience in Design Verification: The candidate has worked as a Design Verification Engineer, which aligns with the job's primary focus.
- Understanding of Low-Power Design: Their experience with low-power design and verification challenges is a strong match for the job requirements.
- Knowledge of Languages and Technologies: Proficiency in languages such as SystemVerilog, UVM, Verilog, C/C++, and Python is a good fit for the job's technical needs.

Missing / Weak Areas:
- Years of Experience: The job description requires 8-12 years of experience, while the candidate's resume indicates a shorter tenure in the industry, with their current role starting in 2022.
- Specific Verification Tasks: The resume does not explicitly mention tasks such as test plan creation, testbench environment setup, or verification at the block, sub-system, and full-chip levels, which are key responsibilities mentioned in the job description.
- Architecture Knowledge: While the candidate has experience with AMBA AXI/APB, the resume does not highlight in-depth knowledge of SOC architecture, which is a requirement for the role.

Suitability Score: 6/10

The candidate's skills and experience show a good foundation for the role, particularly in design verification and low-power design. However, the missing areas and the discrepancy in years of experience suggest that further assessment and additional qualifications may be required to fully meet the job's expectations.

--- GROQ OUTPUT ---

Candidate Summary:
The candidate is a Design Verification Engineer with approximately 1 year of experience in design verification and a background in microelectronic engineering. They have worked with AXI and APB protocols and have experience with languages such as English, Mandarin, and Malay. Their work experience includes roles in design verification, manufacturing, and equipment maintenance.

Matching Skills:
- Experience with AXI and APB protocols
- Background in microelectronic engineering
- Proficiency in English language
- Familiarity with design verification concepts

Missing / Weak Areas:
- Lack of experience in SystemVerilog, UVM, and Verilog
- Limited experience in SOC architecture, low-power design, and verification challenges
- No direct experience with ARM processor-based designs, low-power design techniques, or MIPS
- Limited experience in C-based verification and test automation
- No mention of experience with gate-level simulations, FPGA, or post-silicon bring-up

Suitability Score: 4/10
The candidate has some basic skills that match the job requirements, but they lack significant experience and technical skills required for the Senior Staff Engineer position, such as SystemVerilog, UVM, and low-power design verification. They would need significant training and development to fill the role.

--- HUGGING FACE OUTPUT ---

Candidate Summary:
The candidate is a Design Verification Engineer with 1 year 4 months of experience in the field, currently working at Skyechip Sdn Bhd in Malaysia. They have a background in microelectronic engineering and have worked in various roles, including manufacturing engineer, equipment engineer, and sales associate. However, their experience is limited, and most of their work history is not directly related to design verification.

Matching Skills:
- The candidate has experience with AXI and APB, which are relevant to the job description.
- They have a degree in Microelectronic Engineering, which is relevant to the field of semiconductor design verification.
- They have worked as a Design Verification Engineer, which suggests they have some experience in the field.

Missing / Weak Areas:
- The candidate lacks experience in SystemVerilog, UVM, and Verilog, which are essential skills for the job.
- They have limited experience in design verification, with only 1 year 4 months of experience in the field.
- They do not have experience with SOC architecture, AMBA, DMA, or low-power design techniques, which are required for the job.
- They do not have experience with ARM processor-based designs, which is a preferred technology for the job.
- They lack experience in working with mixed-signal designs, low-power battery-operated designs, and design verification for complex SOC designs.

Suitability Score: 2/10
The candidate's limited experience in design verification, lack of essential skills, and limited relevance of their work history to the job description make them a less suitable candidate for the Senior Staff Engineer - Design Verification position. They would require significant training and development to meet the requirements of the job.

20) Run all resumes through models

In [21]:
results = []

for candidate_name, resume_text in cleaned_resumes.items():
    user_prompt = build_user_prompt(
        job_description=cleaned_job_description,
        candidate_name=candidate_name,
        resume_text=resume_text
    )

    print(f"Processing {candidate_name}...")

    try:
        gemini_output = get_gemini_response(SYSTEM_PROMPT, user_prompt)
    except Exception as e:
        gemini_output = f"Gemini Error: {e}"

    try:
        cohere_output = get_cohere_response(SYSTEM_PROMPT, user_prompt)
    except Exception as e:
        cohere_output = f"Cohere Error: {e}"

    try:
        groq_output = get_groq_response(SYSTEM_PROMPT, user_prompt)
    except Exception as e:
        groq_output = f"Groq Error: {e}"

    try:
        huggingface_output = get_huggingface_response(SYSTEM_PROMPT, user_prompt)
    except Exception as e:
        huggingface_output = f"Hugging Face Error: {e}"

    results.append({
        "candidate_name": candidate_name,
        "gemini_output": gemini_output,
        "cohere_output": cohere_output,
        "groq_output": groq_output,
        "huggingface_output": huggingface_output
    })

print("Done.")

Processing 1 DV.txt...
Processing 2 DV.txt...
Processing 3.txt...
Processing 4.txt...
Processing 5.txt...
Done.

21) View all results

In [22]:
for item in results:
    print("=" * 100)
    print("Candidate:", item["candidate_name"])

    print("\nGEMINI RESPONSE:\n")
    print(item["gemini_output"])

    print("\nCOHERE RESPONSE:\n")
    print(item["cohere_output"])

    print("\nGROQ RESPONSE:\n")
    print(item["groq_output"])

    print("\nHUGGING FACE RESPONSE:\n")
    print(item["huggingface_output"])
    print()

====================================================================================================
Candidate: 1 DV.txt

GEMINI RESPONSE:

**Candidate Summary:**
The candidate holds a Bachelor's degree in Microelectronic Engineering and has 1 year and 4 months of experience as a Design Verification Engineer. Prior experience includes roles in manufacturing engineering, equipment maintenance, sales, and delivery. The resume indicates familiarity with AXI, APB, and CHI protocols.

**Matching Skills:**
*   **Education:** Bachelor of Engineering in Microelectronic Engineering aligns with the BSEE/MSEE degree requirement.
*   **Protocols:** The candidate lists AXI and APB in their top skills, which are key components of the AMBA architecture (AXI/AHB/APB) required by the job description.
*   **Current Role:** Currently employed as a Design Verification Engineer, indicating an entry into the field.

**Missing / Weak Areas:**
*   **Experience Level:** Significantly falls short of the required 8-12 years of experience in semiconductor design verification, with only 1 year 4 months in a relevant DV role. Most other experience is unrelated to design verification.
*   **Detailed DV Experience:** The resume lacks specific details regarding responsibilities and accomplishments in the Design Verification Engineer role. This prevents assessment of critical skills such as:
    *   Developing and executing verification plans for complex SoC designs.
    *   Experience at block, sub-system, and full-chip verification levels.
    *   Creating testbench environments using SV/UVM, integrating VIPs, randomized testing, and scoreboarding.
    *   Utilizing UVM to create drivers, monitors, predictors, and scoreboards.
    *   In-depth knowledge of SoC architecture (beyond basic protocols), DMAs, security, clock, and power-gating techniques.
    *   Writing tests, assertions, and coverage for blocks.
    *   Developing utilities for verification automation, testbench automation, and regression.
    *   Experience with power and performance verification.
    *   Performing gate-level simulations and supporting FPGA/post-silicon bring-up.
    *   Working with mixed-signal designs, low-power design and verification challenges.
    *   C-based verification in an SoC environment.
    *   Proficiency in languages like SystemVerilog, UVM, Verilog, C/C++, Python, and Makefiles for verification.
    *   Experience with ARM processor-based designs.

**Suitability Score:** 2/10

COHERE RESPONSE:

Candidate Summary:
This candidate is a Design Verification Engineer with a background in microelectronic engineering. They have experience in manufacturing, equipment engineering, and design verification. The candidate has worked with various companies, including Intel Corporation and Silterra Malaysia, and has a strong understanding of semiconductor processes and equipment.

Matching Skills:
- Experience in design verification, specifically at the block, sub-system, and full-chip levels.
- Knowledge of AMBA AXI/AHB/APB protocols and DMA flow control.
- Proficiency in languages such as SystemVerilog, Verilog, C/C++, and Python.
- Familiarity with low-power design and verification challenges.
- Understanding of mixed-signal designs and their verification.

Missing / Weak Areas:
- The candidate's resume does not explicitly mention experience with security hardware verification, which is a key aspect of the job description.
- There is no indication of working with IoT applications or systems-on-chip (SoC) designs that include multiple CPUs and digital signal processors.
- While the candidate has worked with low-power designs, the resume lacks details on their experience with battery-operated designs and power-gating techniques.
- The resume does not provide evidence of creating test plans, testbench environments, or integrating VIPs, which are essential tasks for the role.

Suitability Score: 6/10

The candidate has a solid foundation in design verification and relevant technical skills. However, the missing areas of experience, particularly in security hardware and IoT-related verification, may be significant gaps for this specific role.

GROQ RESPONSE:

Candidate Summary:
The candidate is a design verification engineer with approximately 1 year of experience in the field, currently working at Skyechip Sdn Bhd in Malaysia. They have a background in microelectronic engineering and have worked in various roles, including manufacturing engineering, equipment engineering, and sales. However, their experience in design verification is limited to their current role.

Matching Skills:
- The candidate has mentioned "axi" and "apb" in their top skills, which are relevant to the job description.
- They have experience working as a design verification engineer, although the duration is shorter than the 8-12 years required by the job description.
- They have a degree in microelectronic engineering, which is relevant to the field of semiconductor design verification.

Missing / Weak Areas:
- The candidate lacks experience in system-level design verification, having only worked on design verification for a short period.
- There is no mention of experience with SystemVerilog, UVM, or other relevant verification tools and languages, which are required by the job description.
- The candidate's experience is mostly limited to Malaysia, and there is no indication of experience working with international teams or clients.
- The job description requires experience with low-power design and verification challenges, arm processor-based designs, and other specific technologies, which are not mentioned in the candidate's resume.

Suitability Score: 4/10
The candidate has some basic skills and education relevant to the field, but lacks the extensive experience, specific technical skills, and expertise required by the job description. They may be considered for a junior or entry-level position, but are not suitable for a senior staff engineer role at this time.

HUGGING FACE RESPONSE:

Candidate Summary:
The candidate is a Design Verification Engineer with 1 year 4 months of experience in design verification and a background in microelectronic engineering. They have worked with AXI and APB protocols and have experience with languages such as English, Mandarin, and Malay. Their current role involves working on design verification at Skyechip Sdn Bhd in Malaysia.

Matching Skills:
- Experience with AXI and APB protocols, which are required for the job
- Background in microelectronic engineering, which is relevant to the field of semiconductor design verification
- Familiarity with design verification, although the scope and complexity may not fully align with the job description
- Proficiency in English, which is a requirement for the role

Missing / Weak Areas:
- Lack of experience with SystemVerilog, UVM, and Verilog, which are essential skills for the job
- Limited experience with SOC architecture, including AMBA, DMA, and security hardware
- No mention of experience with low-power design and verification challenges, which is a highly desired skill
- No experience with ARM processor-based designs, which is a preferred technology
- Limited experience in the field of semiconductor design verification, with only 1 year 4 months of experience, whereas the job requires 8-12 years of experience

Suitability Score: 2/10
The candidate's limited experience in design verification, lack of essential technical skills, and limited relevance of their work experience to the job description make them a less suitable candidate for the Senior Staff Engineer - Design Verification role.

====================================================================================================
Candidate: 2 DV.txt

GEMINI RESPONSE:

**Candidate Summary:**
The candidate presents a solid background in semiconductor design verification and RTL development, with approximately 9 years of experience. They have held various verification and technical lead roles, including Staff Design Verification Engineer. Their experience includes RTL/SDF simulation, formal verification, DFT, STA, and exposure to AMBA protocols (AXI/AHB/APB). The candidate's educational background aligns with the job's requirement for a BSEE/MSEE degree.

**Matching Skills:**
*   **Total Experience:** Approximately 9 years in verification-related roles, falling within the 8-12 years required for a Sr. Staff role.
*   **Education:** Bachelor's degree in Electrical and Electronics Engineering.
*   **Verification Levels:** Experience at block, sub-system, and full-chip levels is implied through various roles and responsibilities like "integration system control block in CPU sub-system" and general verification tasks.
*   **AMBA Protocols:** Explicitly mentions AXI/AHB/APB experience.
*   **Clock/Power Control:** Has experience with "clock controller, power control, clock and power hardmacro integration" from a design perspective, which provides a good foundation.
*   **Simulation & Formal Verification:** Experience with RTL/SDF simulation and formal verification/analyzing.
*   **Gate-Level Simulations:** "RTL/SDF simulation" suggests experience with gate-level simulations.
*   **FPGA:** Lists "FPGA" as a skill, which may contribute to supporting bring-up.

**Missing / Weak Areas:**
*   **UVM Methodology:** The candidate explicitly mentions "VMM methodology" but does not demonstrate experience with UVM, which is a *required* skill for developing drivers, monitors, predictors, and scoreboards in the job description. This is a significant gap for a Sr. Staff role.
*   **C-based Verification:** Not mentioned in the resume, yet it is a *required* skill for the role.
*   **Mixed-Signal Design Verification:** Not explicitly stated as an area of experience.
*   **Low-Power Design Verification:** While they have experience with power control design, explicit verification experience for low-power battery-operated designs using advanced DV techniques is not detailed.
*   **Advanced DV Techniques:** No explicit mention of developing verification plans, assertions, achieving coverage goals, or developing support utilities for verification automation/regression.
*   **Languages (C/C++, Python, Makefile):** C/C++ is not mentioned, and Python/Makefile are absent from the resume.
*   **SoC Architectures & IPs:** While AMBA is present, specific experience with DMAs, security hardware, specific serial devices, QoS, MIPI, Crypto, OTP, or DSP verification is not highlighted.
*   **ARM Processor-Based Designs:** Not explicitly mentioned as an area of experience, although they worked on a "CPU sub-system."

**Suitability Score:** 5/10

COHERE RESPONSE:

Candidate Summary:
This candidate has a strong background in RTL design, verification, and development, with a focus on semiconductor and SoC (System-on-Chip) projects. They have experience in various aspects of the design process, including RTL coding, verification, and integration.

Matching Skills:
- RTL Coding and Verification: The candidate has extensive experience in RTL design and verification, which is a key requirement for the role.
- SystemVerilog and UVM: Proficiency in these languages is evident from their work history, aligning with the job's needs.
- Mixed-Signal Design: The candidate's experience includes working with mixed-signal designs, which is a plus for the role.
- Low-Power Design: Their exposure to low-power design and verification techniques is a strong match for the job description.
- ARM Processor-Based Designs: Experience with ARM-based designs is an advantage, as the job requires knowledge of ARM SOC.

Missing / Weak Areas:
- Lack of Specifics: The resume provides limited details about the candidate's involvement in full-chip verification and their role in creating test plans, testbench environments, and automated testing.
- Missing Technologies: While the candidate has experience with some preferred technologies like AXI/AHB/APB, there is no mention of their expertise in other key technologies like MIPI, Crypto, or DSP.
- Limited Leadership Experience: The role is for a senior staff engineer, and while the candidate has held senior positions, their resume does not highlight any significant leadership or team management experience.

Suitability Score: 7/10

GROQ RESPONSE:

Candidate Summary:
The candidate has around 12 years of experience in the field of semiconductor design verification, with a strong background in RTL coding, verification, and development. They have worked with various companies, including Renesas Design Vietnam Co. Ltd., HCL Technologies, and Bos Semiconductors, and have experience with system control blocks, CPU sub-systems, and low-power design techniques.

Matching Skills:
- Relevant technical skills: SystemVerilog, UVM, Verilog, C/C++, Python, and experience with Arm processor-based designs.
- Experience with design verification for digital and mixed-signal designs, including systems-on-chip with multiple CPUs and digital signal processors.
- Knowledge of SOC architecture, including AMBA AXI/AHB/APB, DMA, and security clock and power-gating techniques.
- Experience with gate-level simulations, regression testing, and testbench automation.

Missing / Weak Areas:
- Limited experience with specifically mentioned technologies such as MIPS, CSI/DSI, Crypto, OTP, DSP, and low-power design verification for battery-operated designs.
- No explicit mention of experience with 3rd party IP/SVIP integration, although they have worked with various IPs and architectures.
- Some gaps in specific tools and methodologies mentioned in the job description, such as VMM methodology and formal verification tools.

Suitability Score: 8/10
The candidate's strong technical background and experience in design verification make them a suitable candidate for the role. However, some gaps in specific technologies and methodologies mentioned in the job description may require additional training or experience. Overall, the candidate's skills and experience align well with the job requirements, making them a strong contender for the position.

HUGGING FACE RESPONSE:

Candidate Summary:
The candidate has approximately 10 years of experience in the field of semiconductor design verification, with a strong background in RTL coding, verification, and development. They have worked with various companies, including Renesas Design Vietnam Co., Ltd., HCL Technologies, and Ampere, and have experience with system control blocks, clock controllers, and power control.

Matching Skills:
- Experience with RTL verification and development
- Familiarity with AXI/AHB/APB protocols
- Knowledge of system control blocks and clock structures
- Experience with formal verification and static timing analysis (STA)
- Proficiency in languages such as SystemVerilog, Verilog, and C/C++
- Experience with FPGA and low-power design

Missing / Weak Areas:
- Lack of explicit experience with UVM (Universal Verification Methodology) and VIPs (Verification Intellectual Properties)
- Limited experience with mixed-signal designs and low-power battery-operated designs
- No mention of experience with ARM processor-based designs or specific low-power design techniques
- No clear evidence of experience with testbench automation, regression, or scoreboarding
- Limited experience with SystemVerilog simulation and verification automation

Suitability Score: 6.5/10
The candidate has a strong foundation in RTL verification and development, but lacks specific experience in some areas, such as UVM, mixed-signal designs, and low-power battery-operated designs. They also have limited experience with testbench automation and verification automation, which are crucial skills for the job. However, their overall experience and skills make them a potential candidate for the role, and they may be able to learn and adapt to the specific requirements of the job.

====================================================================================================
Candidate: 3.txt

GEMINI RESPONSE:

**Candidate Summary:**
An experienced Design Verification professional with over 9 years of experience, including 3+ years in a leadership role. The candidate demonstrates strong expertise in SystemVerilog, UVM, and SoC verification, particularly at the top-level and with key bus architectures like AXI/AHB/APB. Their background includes developing virtual platforms, integrating IPs/VIPs, and working on secure automotive solutions, which aligns well with the Sr. Staff Engineer Design Verification role.

**Matching Skills:**
*   **Experience Level**: Over 9 years of relevant experience, fitting the 8-12 year requirement.
*   **Verification Methodology**: Strong proficiency in SystemVerilog and UVM, including creating testbenches and integrating VIPs.
*   **SoC Verification**: Demonstrated experience in block, sub-system, and top-level verification for complex chips (e.g., secure car access solution).
*   **SoC Architecture Knowledge**: Experience with AMBA AXI/AHB/APB bus systems and concepts related to security hardware.
*   **Languages**: Proficient in SystemVerilog, UVM, Verilog, C/C++, and Python.
*   **IP Integration**: Experience in integrating various IPs and VIPs within verification environments.
*   **Leadership Experience**: 3+ years as an RTL Design Verification Leader, including project management.
*   **Mixed-Signal Exposure**: Mentions RF in a project, indicating some exposure to mixed-signal designs.
*   **FPGA Experience**: Experience in developing IP-cores for FPGA.
*   **C-based Verification**: Experience in C++ for virtual platform development, supporting C-based verification.

**Missing / Weak Areas:**
*   **Low-Power DV Challenges**: While LPDDR4/5 is mentioned, explicit detailed experience in verifying low-power battery-operated designs and specific power-gating techniques is not clearly articulated.
*   **Gate-Level Simulations**: Not explicitly mentioned in the resume.
*   **Post-Silicon Bring-up**: While FPGA experience is present, specific experience with post-silicon bring-up is not detailed.
*   **Assertions and Coverage Goals**: These are fundamental to DV, but explicit mention of writing assertions or creating tests to achieve coverage goals is missing.
*   **DMA**: Mentioned in the job description, but not explicitly highlighted in the candidate's projects.
*   **Makefile**: Listed as a required language in the JD, but not explicitly mentioned in the resume.
*   **ARM Processor-based Designs**: Implied by automotive ECU work, but not explicitly stated as ARM processor experience.
*   **Developing tests for power and performance aspects**: Not explicitly stated as a responsibility.

**Suitability Score:** 8.5/10

COHERE RESPONSE:

Candidate Summary:
This candidate has experience in design verification, with a focus on hardware and RTL design. They have worked on various projects involving automotive chips, secure access solutions, and image processing algorithms. The candidate has a strong background in languages such as C++, Verilog, and SystemVerilog, and has managed a team of 8 members.

Matching Skills:
- Proficiency in SystemVerilog and UVM for design verification tasks.
- Experience with hardware verification, including top-level verification and HLS verification/design.
- Knowledge of RTL design and understanding of various IP cores and bus systems (AXI, AHB, APB).
- Project management skills and experience leading a team.
- Familiarity with low-power design and verification challenges.

Missing / Weak Areas:
- The candidate's resume does not explicitly mention experience with mixed-signal designs, which is a key requirement in the job description.
- There is no indication of work with security hardware or IoT applications, which are specific responsibilities mentioned in the job role.
- While the candidate has worked with SystemVerilog, there is no mention of experience with SystemC, which is preferred in the job description.

### **Recomendation Section**

22. Score Extraction

In [23]:
def extract_score(text):
    """
    Extracts a score out of 10 from model output.
    Handles cases like:
    7/10
    7.5/10
    Suitability Score: 6/10
    """
    if not isinstance(text, str):
        return None

    match = re.search(r'(\d+(?:\.\d+)?)\s*/\s*10', text)
    if match:
        return float(match.group(1))

    return None

23. Score Table

In [24]:
score_rows = []

for item in results:
    score_rows.append({
        "candidate_name": item["candidate_name"],
        "gemini_score": extract_score(item["gemini_output"]),
        "cohere_score": extract_score(item["cohere_output"]),
        "groq_score": extract_score(item["groq_output"]),
        "huggingface_score": extract_score(item["huggingface_output"]),
    })

scores_df = pd.DataFrame(score_rows)
scores_df

  candidate_name  gemini_score  cohere_score  groq_score  huggingface_score
0       1 DV.txt           2.0           6.0         4.0                2.0
1       2 DV.txt           5.0           7.0         8.0                6.5
2          3.txt           8.5           6.0         7.5                7.5
3          4.txt           3.0           5.0         NaN                4.0
4          5.txt           2.0           6.0         4.0                4.0

24. Average Score

In [25]:
score_columns = ["gemini_score", "cohere_score", "groq_score", "huggingface_score"]

scores_df["average_score"] = scores_df[score_columns].mean(axis=1, skipna=True)
scores_df = scores_df.sort_values(by="average_score", ascending=False)

scores_df

,candidate_name,gemini_score,cohere_score,groq_score,huggingface_score,average_score
2,3.txt,8.5,6.0,7.5,7.5,7.375
1,2 DV.txt,5.0,7.0,8.0,6.5,6.625
3,4.txt,3.0,5.0,NaN,4.0,4.000
4,5.txt,2.0,6.0,4.0,4.0,4.000
0,1 DV.txt,2.0,6.0,4.0,2.0,3.500

25. Each Model's Top Reccomendation

In [26]:
# model_recommendations = {}

# for col in score_columns:
#     valid_df = scores_df.dropna(subset=[col])
#     if not valid_df.empty:
#         top_candidate = valid_df.sort_values(by=col, ascending=False).iloc[0]["candidate_name"]
#         model_recommendations[col] = top_candidate

# print("Top recommendation by each LLM:\n")
# for model_name, candidate in model_recommendations.items():
#     print(f"{model_name}: {candidate}")

26. Majority Vote

In [27]:
# from collections import Counter

# votes = list(model_recommendations.values())
# vote_counter = Counter(votes)

# print("Majority vote result:\n")
# for candidate, count in vote_counter.items():
#     print(f"{candidate}: {count} vote(s)")

# majority_best_candidate = vote_counter.most_common(1)[0][0]
# print("\nBest resume based on majority vote:", majority_best_candidate)

27. Final Best Candidate

In [28]:
# best_average_candidate = scores_df.iloc[0]["candidate_name"]
# print("Best resume based on average score:", best_average_candidate)

# if majority_best_candidate == best_average_candidate:
#     final_best_candidate = majority_best_candidate
# else:
#     # if majority and average differ, prefer average score
#     final_best_candidate = best_average_candidate

# print("FINAL RECOMMENDED RESUME:", final_best_candidate)

ALL COMBINED RESULTS TESTING

In [29]:
from collections import Counter

score_columns = ["gemini_score", "cohere_score", "groq_score", "huggingface_score"]

# Find top candidate for each model
model_recommendations = {}

for col in score_columns:
    valid_df = scores_df.dropna(subset=[col])
    if not valid_df.empty:
        top_candidate = valid_df.sort_values(by=col, ascending=False).iloc[0]["candidate_name"]
        model_recommendations[col] = top_candidate

print("Top recommendation by each LLM:\n")
for model_name, candidate in model_recommendations.items():
    print(f"{model_name}: {candidate}")

# Majority vote
votes = list(model_recommendations.values())
vote_counter = Counter(votes)

print("\nMajority vote result:\n")
for candidate, count in vote_counter.items():
    print(f"{candidate}: {count} vote(s)")

majority_best_candidate = vote_counter.most_common(1)[0][0]

# Best candidate by average score
best_average_candidate = scores_df.sort_values(by="average_score", ascending=False).iloc[0]["candidate_name"]

print("\nBest resume based on average score:", best_average_candidate)

# Final decision
if majority_best_candidate == best_average_candidate:
    final_best_candidate = majority_best_candidate
else:
    final_best_candidate = best_average_candidate

print("\nFINAL RECOMMENDED RESUME:", final_best_candidate)

Top recommendation by each LLM:

gemini_score: 3.txt
cohere_score: 2 DV.txt
groq_score: 2 DV.txt
huggingface_score: 3.txt

Majority vote result:

3.txt: 2 vote(s)
2 DV.txt: 2 vote(s)

Best resume based on average score: 3.txt

FINAL RECOMMENDED RESUME: 3.txt

28) Save results to CSV

In [30]:
results_df = pd.DataFrame(results)
results_df.to_csv("week1_2_llm_screening_results.csv", index=False)

print("Saved: week1_2_llm_screening_results.csv")
results_df

Saved: week1_2_llm_screening_results.csv

,candidate_name,gemini_output,cohere_output,groq_output,huggingface_output
0,1 DV.txt,**Candidate Summary:**\nThe candidate holds a ...,Candidate Summary: \nThis candidate is a Desig...,Candidate Summary:\nThe candidate is a design ...,Candidate Summary:\nThe candidate is a Design ...
1,2 DV.txt,**Candidate Summary:**\nThe candidate presents...,Candidate Summary:\nThis candidate has a stron...,Candidate Summary:\nThe candidate has around 1...,Candidate Summary:\nThe candidate has approxim...
2,3.txt,**Candidate Summary:**\nAn experienced Design ...,Candidate Summary:\nThis candidate has experie...,Candidate Summary:\nThe candidate has approxim...,Candidate Summary:\nThe candidate is an experi...
3,4.txt,**Candidate Summary:**\nThe candidate holds an...,Candidate Summary: \nThis candidate has a stro...,Candidate Summary:\nThe candidate has a master...,Candidate Summary:\nThe candidate has a backgr...
4,5.txt,**Candidate Summary:**\nThe candidate is an ex...,Candidate Summary:\nThe candidate is an experi...,Candidate Summary:\nThe candidate is an experi...,Candidate Summary:\nThe candidate is an experi...

29) Save results to JSON too

In [31]:
with open("week1_2_llm_screening_results.json", "w", encoding="utf-8") as f:
    json.dump(results, f, indent=2, ensure_ascii=False)

print("Saved: week1_2_llm_screening_results.json")

Saved: week1_2_llm_screening_results.json

30) Download outputs from Colab

In [32]:
files.download("week1_2_llm_screening_results.csv")
files.download("week1_2_llm_screening_results.json")

preprcessing testing

In [33]:
candidate = list(raw_resumes.keys())[0]

print("RAW TEXT:\n")
print(raw_resumes[candidate][:500])

print("\n" + "="*60 + "\n")

print("CLEANED TEXT:\n")
print(cleaned_resumes[candidate][:500])

RAW TEXT:


Top Skills
AXI
APB
CHI
Languages
English  (Native or Bilingual)
Mandarin  (Limited Working)
Malay  (Native or Bilingual)
Design Verification Engineer
Kulim, Kedah, Malaysia
Summary
Currently working as Design Verification Engineer at Skyechip Sdn
Bhd
Graduated from University of Malaysia Perlis (UniMAP), majoring in
Microelectronic Engineering.
Experience
SkyeChip
Design Verification Engineer
August 2022-Present (1 year 4 months)
Penang, Malaysia
Fuji Electric (M) Sdn Bhd
Manufacturing Engin

============================================================

CLEANED TEXT:

top skills axi apb chi languages english native or bilingual mandarin limited working malay native or bilingual design verification engineer kulim kedah malaysia summary currently working as design verification engineer at skyechip sdn bhd graduated from university of malaysia perlis unimap majoring in microelectronic engineering. experience skyechip design verification engineer august 2022-present 1 year 4 months penang malaysia fuji electric m sdn bhd manufacturing engineer april 2022-august 2

In [34]:
for name in raw_resumes:
    raw_len = len(raw_resumes[name])
    clean_len = len(cleaned_resumes[name])

    print(name)
    print("Raw length:", raw_len)
    print("Cleaned length:", clean_len)
    print("Removed characters:", raw_len - clean_len)
    print()

1 DV.txt
Raw length: 2974
Cleaned length: 2883
Removed characters: 91

2 DV.txt
Raw length: 1403
Cleaned length: 1362
Removed characters: 41

3.txt
Raw length: 1699
Cleaned length: 1646
Removed characters: 53

4.txt
Raw length: 4800
Cleaned length: 4692
Removed characters: 108

5.txt
Raw length: 4376
Cleaned length: 4215
Removed characters: 161

In [35]:
import re

for name, text in cleaned_resumes.items():
    emails = re.findall(r'\S+@\S+', text)

    if emails:
        print(name, "Still has email:", emails)
    else:
        print(name, "No emails found")

1 DV.txt No emails found
2 DV.txt No emails found
3.txt No emails found
4.txt No emails found
5.txt No emails found